"""Content for the global, country and India-city pages.

Every page's copy lives here as data; build_geo.py turns it into
<slug>.body.html files and the built embeds in out/.

Wording follows the market each page is written for: US pages use
American spelling and American hiring vocabulary (resume, W-2, EOR,
US GAAP), UK pages use CV and IR35, UAE pages use Emiratisation and
MOHRE, Singapore pages use MOM passes and CPF, Australia pages use
superannuation and Fair Work. SPELL_US at the bottom catches shared
boilerplate on the American pages.

Copy rules (October 2026): one or two sentences per block, four FAQs
per page with one-sentence answers, no em or en dashes.
"""

# ---------------------------------------------------------------- COUNTRIES
COUNTRIES = {
    "us": dict(
        name="the US", formal="the United States", lang="en-US", spell="us",
        path="/us", currency="USD", nav="United States",
        kw="India recruitment agency for US companies",
        eyebrow="Hiring in India from the United States",
        h1_a="India recruitment for US companies.",
        h1_b="Finance, data and AI teams in Bengaluru.",
        lead="Deep talent, and a working day that starts while New York sleeps. We run the search end to end and hand you a shortlist you can interview.",
        short="Women-led search firm in Bengaluru hiring finance, analytics and AI talent in India for US companies, with interview loops run around your time zone.",
        why_h="What US teams come to us for.",
        why_body="Three good people in India, quickly, with nobody in-house who can read an Indian resume. That is the gap we fill.",
        why_items=[
            ("US companies hiring their first India team", "a controller, an FP&amp;A lead or two data engineers, before there is an India HR function."),
            ("CFOs moving close or planning work offshore", "people who have run US GAAP close cycles and can talk to your auditors."),
            ("GCC leaders scaling a center", "the next layer of managers once the first twenty seats are full."),
        ],
        roles=[("Finance &amp; accounting", "Controller, record-to-report lead, US GAAP reporting manager, AR and AP leads", "Manager to Director"),
               ("FP&amp;A", "FP&amp;A manager, business finance partner, revenue analyst", "Analyst to Senior Manager"),
               ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, data scientist", "Senior IC to Head"),
               ("AI &amp; ML", "ML engineer, applied scientist, LLM and platform engineers", "Senior IC to Lead"),
               ("Technology", "Backend, full-stack, DevOps, QA automation, engineering manager", "Mid to Director"),
               ("Leadership", "India site head, country finance head, center director", "Director to VP")],
        method_h="A shortlist you can take straight into a loop.",
        method_lede="Four or five names, each with a note on fit and cost.",
        method_body="We interview before you do. Every profile carries current pay in INR, notice period, the reason for moving and how the experience maps onto US reporting standards.",
        comp_h="Payroll, entity and the paperwork.",
        comp_lede="You do not need an Indian entity to make the first hire.",
        comp_cards=[("No entity yet", "Employer of record", "First hires go on an EOR or a staffing payroll, with offers written to transfer cleanly to your entity later."),
                    ("Scaling up", "Your own India entity", "Once you have a private limited company and a payroll provider, we hire onto your books under Indian statutory norms."),
                    ("Either way", "Contract and IP", "We flag the clauses US counsel asks about: IP assignment, non-solicit limits under Indian law and what a 90-day notice period does to your start date.")],
        tz_h="The overlap problem, solved in the offer.",
        tz_body="India is 9.5 to 12.5 hours ahead of the US mainland. Most finance and analytics hires settle on a 2pm to 11pm IST day, and we tell you which candidates will take a 7am Eastern stand-up.",
        tz_chips=["Eastern 8:30am = 6pm IST", "Central 8am = 6:30pm IST", "Pacific 7am = 7:30pm IST", "Hybrid 2pm to 11pm IST"],
        faqs=[("Can you hire in India if we have no Indian entity?",
               "Yes. Most US clients make their first hires through an employer of record, then move people onto their own entity without resetting tenure or benefits."),
              ("How long does a search take?",
               "Four to six weeks from brief to signed offer for specialist roles, six to ten for leadership, plus a notice period of 60 to 90 days."),
              ("Will candidates work US hours?",
               "Many will take a 2pm to 11pm IST shift; full overnight shifts narrow the pool and cost 15 to 25 percent more."),
              ("What are your fees?",
               "A percentage of annual fixed pay for contingency, a staged fee for retained leadership search, and a monthly rate for dedicated team hiring, all agreed in writing first.")],
        cta_a="Hiring in India this quarter?", cta_b="Let's scope it.",
        cta_copy="Send us the role, the reporting line and the time-zone expectation. You will get a market read and a suggested approach.",
    ),
    "uk": dict(
        name="the UK", formal="the United Kingdom", lang="en-GB", spell="gb",
        path="/uk", currency="GBP", nav="United Kingdom",
        kw="India recruitment agency for UK companies",
        eyebrow="Hiring in India from the United Kingdom",
        h1_a="India recruitment for UK companies.",
        h1_b="Finance, analytics and AI hires that stay.",
        lead="The easy India talent has been hired several times over. We work the harder end: qualified accountants, FP&amp;A managers, analytics leads and AI engineers who stay past the first appraisal.",
        short="Women-led search firm in Bengaluru hiring finance, analytics and AI talent in India for UK companies, on a 4.5 to 5.5 hour time difference that suits both sides.",
        why_h="Where UK clients usually need us.",
        why_body="A London hiring manager cannot tell a strong Indian CV from a well-written one, and most agencies send fifty of both.",
        why_items=[
            ("UK groups setting up a shared service centre", "a finance manager and a controller first, then the team underneath them."),
            ("Finance directors consolidating group reporting", "people fluent in IFRS and UK GAAP who have closed books for a UK parent."),
            ("Heads of data", "analytics and engineering hires who can hold their own with the UK business."),
        ],
        roles=[("Finance &amp; accounting", "Financial controller, group reporting manager, R2R lead, qualified accountants (ACA, ACCA, CIMA, CA)", "Manager to Director"),
               ("FP&amp;A", "FP&amp;A manager, commercial finance partner, management accountant", "Analyst to Senior Manager"),
               ("Data &amp; analytics", "Analytics lead, data engineer, BI manager, data scientist", "Senior IC to Head"),
               ("AI &amp; ML", "ML engineer, applied scientist, MLOps", "Senior IC to Lead"),
               ("Risk &amp; compliance", "Internal audit, financial crime, regulatory reporting", "Manager to Director"),
               ("Leadership", "India centre head, finance head, delivery director", "Director to VP")],
        method_h="Six CVs, each one worth reading.",
        method_lede="Four strong profiles beat twenty on a Friday.",
        method_body="Each CV arrives with current and expected pay in INR, notice period, what the candidate owns today and where they are weak. When a brief is priced below the market, we say so.",
        comp_h="Entity, payroll and the compliance questions.",
        comp_lede="UK finance teams ask the same questions, so here they are answered.",
        comp_cards=[("Before the entity", "Employer of record", "Early hires sit with an EOR while the Indian subsidiary is incorporated, with offers that move onto your payroll without renegotiation."),
                    ("On your books", "Indian statutory pay", "Provident fund, gratuity, leave encashment and a 30 to 90 day notice period. These are permanent employees of an Indian company."),
                    ("Where it applies", "Contractors", "An Indian contractor is tested under Indian employment law, not IR35, and we will say when a role is better as a permanent hire.")],
        tz_h="Four and a half hours is the whole advantage.",
        tz_body="India is 5.5 hours ahead of the UK in winter and 4.5 in summer. Most candidates we place work 12.30pm to 9.30pm IST, with real overlap from lunchtime onwards.",
        tz_chips=["London 9am = 2.30pm IST", "London 1pm = 6.30pm IST", "BST: 4.5 hours", "GMT: 5.5 hours"],
        faqs=[("Do we need an Indian entity to hire?",
               "No. An employer of record covers the first few hires; once you have an Indian entity and payroll, we hire directly onto your books."),
              ("How long is a search, start to finish?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period for senior staff."),
              ("Does IR35 apply to our India hires?",
               "No. IR35 is a UK tax rule; Indian employees are employed under Indian law by your entity or an employer of record."),
              ("Can you run a confidential search?",
               "Yes. Leadership and replacement hires are usually retained and run without naming you until the candidate has signed an NDA.")],
        cta_a="Building an India team?", cta_b="Start with the brief.",
        cta_copy="Tell us the role, who it reports to in the UK and the approved pay range. We will say whether it is winnable and how we would run it.",
    ),
    "uae": dict(
        name="the UAE", formal="the United Arab Emirates", lang="en-AE", spell="gb",
        path="/uae", currency="AED", nav="UAE",
        kw="recruitment agency for UAE companies",
        eyebrow="Hiring from the UAE",
        h1_a="Recruitment for UAE companies.",
        h1_b="Finance hires for Dubai and Abu Dhabi, and India back-office teams.",
        lead="We hire finance, analytics and AI people for UAE businesses, whether the seat is in Dubai, Abu Dhabi or a back office in Bengaluru.",
        short="Women-led search firm in Bengaluru hiring finance, analytics and AI talent for UAE companies: relocation hires to the Gulf, and India back offices for Gulf groups.",
        why_h="Two kinds of UAE mandate.",
        why_body="Either you are hiring someone into the Emirates, usually from India, or you are building a finance and analytics team in India to support the Gulf business. We run both.",
        why_items=[
            ("Family groups and holding companies", "a group financial controller or FP&amp;A head who has worked across several entities."),
            ("DIFC and ADGM regulated firms", "finance, risk and compliance hires who understand the regulator."),
            ("UAE businesses building an India back office", "a shared service team for accounting, reporting and analytics on Gulf working hours."),
        ],
        roles=[("Group finance", "Group financial controller, consolidation manager, finance manager, chief accountant", "Manager to Director"),
               ("FP&amp;A &amp; commercial", "FP&amp;A head, budgeting manager, cost controller, commercial analyst", "Analyst to Head"),
               ("Treasury &amp; risk", "Treasury manager, credit control head, internal audit, compliance officer", "Manager to Director"),
               ("Data &amp; analytics", "Analytics manager, BI lead, data engineer", "Senior IC to Head"),
               ("AI &amp; technology", "ML engineer, data platform engineer, ERP and systems leads", "Senior IC to Lead"),
               ("Leadership", "CFO, finance director, India centre head for a Gulf group", "Director to CFO")],
        method_h="Candidates who will actually move, at a number that works.",
        method_lede="A Gulf offer is a family decision.",
        method_body="For relocation hires we test schooling, spouse employment and the all-in package early. For India-based hires we benchmark against the GCCs in the same city.",
        comp_h="Visas, Emiratisation and the package.",
        comp_lede="The compliance layer is yours, but we will not send candidates who break it.",
        comp_cards=[("Mainland and free zone", "Work permits and visas", "Visas are sponsored by your entity through MOHRE or by the free zone authority; we confirm each candidate's status before shortlisting."),
                    ("Where they apply", "Emiratisation targets", "If a seat is earmarked for an Emirati national, say so at the brief and we run that search separately."),
                    ("Every offer", "Package, not salary", "Basic, housing, schooling, flights and gratuity, presented as an all-in annual AED figure against the candidate's current net position.")],
        tz_h="Same week, ninety minutes apart.",
        tz_body="India is 1.5 hours ahead of the UAE and both run a Monday to Friday week, so an India team is effectively inside the same working day.",
        tz_chips=["Dubai 9am = 10.30am IST", "Dubai 5pm = 6.30pm IST", "Monday to Friday both sides", "Direct flights, three hours"],
        faqs=[("Do you place candidates inside the UAE or only in India?",
               "Both: India-based candidates for relocation to Dubai, Abu Dhabi and Sharjah, and India-based teams for UAE groups."),
              ("Can you help with the employment visa?",
               "The filing sits with your entity or PRO; we confirm every candidate's status, notice period and documentation before offer stage."),
              ("How do you handle Emiratisation quotas?",
               "A role reserved for an Emirati national runs as a separate search with its own sourcing approach."),
              ("How quickly can someone start?",
               "Plan on eight to twelve weeks from signed offer to first day in the Gulf, covering notice period and visa processing.")],
        cta_a="Hiring for Dubai, Abu Dhabi or an India back office?", cta_b="Tell us which.",
        cta_copy="Send the role, the entity it sits in and the package band. We will tell you what the market looks like and how we would run the search.",
    ),
    "singapore": dict(
        name="Singapore", formal="Singapore", lang="en-SG", spell="gb",
        path="/singapore", currency="SGD", nav="Singapore",
        kw="recruitment agency for Singapore companies",
        eyebrow="Hiring from Singapore",
        h1_a="Recruitment for Singapore companies.",
        h1_b="India teams, and regional finance hires.",
        lead="Singapore is where the regional CFO sits and India is where the team gets built. We hire finance, analytics and AI talent in India for Singapore-headquartered businesses.",
        short="Women-led search firm in Bengaluru hiring finance, analytics and AI talent in India for Singapore companies, with a full shared afternoon on a 2.5 hour difference.",
        why_h="Why Singapore teams hire in India.",
        why_body="Local hiring is tight and head-office budgets rarely stretch to a full regional finance team. India gives depth at a cost that works, provided someone senior does the filtering.",
        why_items=[
            ("Regional CFOs and finance directors", "a controller, a consolidation manager and an FP&amp;A team in India reporting into Singapore."),
            ("Fintech, trading and commodity firms", "product control, treasury operations and regulatory reporting talent."),
            ("Heads of data and engineering", "analytics and AI hires in Bengaluru or Hyderabad who can work a full Singapore day."),
        ],
        roles=[("Finance &amp; accounting", "Financial controller, consolidation manager, R2R lead, chartered accountants", "Manager to Director"),
               ("FP&amp;A", "FP&amp;A manager, regional business partner, management reporting lead", "Analyst to Senior Manager"),
               ("Treasury &amp; product control", "Treasury operations, product control, reconciliations, regulatory reporting", "Analyst to Head"),
               ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, data scientist", "Senior IC to Head"),
               ("AI &amp; ML", "ML engineer, applied scientist, data platform engineer", "Senior IC to Lead"),
               ("Leadership", "India site head, regional finance head, shared services director", "Director to VP")],
        method_h="One recruiter, from brief to joining day.",
        method_lede="You will not be handed to an account manager after the kick-off call.",
        method_body="The person who takes your brief runs the search, interviews the candidates and stays on the offer. If the brief is unwinnable at the approved band, we say so in week one.",
        comp_h="Employment, payroll and the rules that matter.",
        comp_lede="Two sets of rules: Singapore's for passes, India's for employment.",
        comp_cards=[("Hiring into Singapore", "Employment Pass and S Pass", "The pass framework sits with your HR team, and we will say plainly when a role is unlikely to clear the qualifying salary."),
                    ("Most common", "India hiring, no entity needed", "Early hires go through an employer of record or our payroll; the statutory items are provident fund and gratuity, not CPF."),
                    ("Scaling", "Shared services build-out", "For a full India centre we hire in waves: leadership first, then process owners, then the analyst layer.")],
        tz_h="A full working afternoon in common.",
        tz_body="Singapore is 2.5 hours ahead of India. Most teams settle on an 11am to 8pm IST day, which covers the whole Singapore afternoon and month-end close.",
        tz_chips=["SG 9am = 6.30am IST", "SG 2pm = 11.30am IST", "SG 6pm = 3.30pm IST", "Hybrid 11am to 8pm IST"],
        faqs=[("Can you hire in India without setting up an entity?",
               "Yes. An employer of record or our staffing payroll covers the first hires, and we move people onto your Indian entity when it is ready."),
              ("Should this role be in Singapore or in India?",
               "Singapore if it needs a local licence or a regulator relationship; India for reporting, controllership or engineering, where the same cost buys a more experienced person."),
              ("What is the equivalent of CPF in India?",
               "Provident fund, plus gratuity after five years of service, both included in the cost-to-company figure on every shortlist."),
              ("How long does a search take?",
               "Four to six weeks from brief to signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period for senior staff.")],
        cta_a="Planning an India team from Singapore?", cta_b="Let's map it.",
        cta_copy="Share the role, the Singapore reporting line and the shift expectation. We will come back with a market read and an approach.",
    ),
    "australia": dict(
        name="Australia", formal="Australia", lang="en-AU", spell="gb",
        path="/australia", currency="AUD", nav="Australia",
        kw="recruitment agency for Australian companies",
        eyebrow="Hiring from Australia",
        h1_a="Recruitment for Australian companies.",
        h1_b="India finance, analytics and AI teams.",
        lead="Australia has run short of accountants and data people. We hire finance, analytics and AI talent in India for Australian companies, on a working day that lines up better than most expect.",
        short="Women-led search firm in Bengaluru hiring finance, analytics and AI talent in India for Australian companies, benchmarked against the GCCs competing for the same people.",
        why_h="What Australian clients are solving for.",
        why_body="The shortage at home is real. The risk is an India team that needs more supervision than it saves, which is a hiring problem, not an offshoring one.",
        why_items=[
            ("Accounting and advisory firms", "qualified accountants and bookkeeping teams who work in Xero, MYOB and the client's workpapers."),
            ("CFOs of listed and PE-backed businesses", "controllership and statutory reporting hires familiar with IFRS."),
            ("Heads of data and product", "analytics, data engineering and ML hires in Bengaluru, Hyderabad or Pune."),
        ],
        roles=[("Finance &amp; accounting", "Financial controller, statutory reporting manager, R2R lead, chartered accountants", "Manager to Director"),
               ("Outsourced accounting", "Accounts preparation, bookkeeping leads, tax support, workpaper reviewers", "Associate to Manager"),
               ("FP&amp;A", "FP&amp;A manager, commercial analyst, budgeting and forecasting lead", "Analyst to Senior Manager"),
               ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, data scientist", "Senior IC to Head"),
               ("AI &amp; ML", "ML engineer, applied scientist, MLOps", "Senior IC to Lead"),
               ("Leadership", "India site head, offshore delivery head, finance head", "Director to VP")],
        method_h="Hire the supervisor before the team.",
        method_lede="Offshore teams fail when the only senior person is in Australia.",
        method_body="We push most clients to hire a manager in India first and build underneath them. Shortlists carry current pay in INR, notice period and the systems the candidate has actually used.",
        comp_h="Employment, payroll and the compliance questions.",
        comp_lede="Your India hires are employed under Indian law, not the Fair Work Act.",
        comp_cards=[("No India entity", "Employer of record", "Early hires sit on an EOR or our payroll, with offers written so moving to your own entity later changes nothing for the employee."),
                    ("What replaces super", "Indian statutory items", "Provident fund and gratuity replace superannuation, notice periods of 30 to 90 days are normal, and awards and penalty rates do not apply."),
                    ("Professional services", "Data and client confidentiality", "Accounting firms usually need client-data terms and a confidentiality undertaking per candidate, which we raise at the brief.")],
        tz_h="Mornings in Sydney, afternoons in Bengaluru.",
        tz_body="India is 4.5 to 5.5 hours behind eastern Australia. A 2pm Sydney call is 8.30am IST, so most teams keep the Australian afternoon for shared work.",
        tz_chips=["Sydney 2pm = 8.30am IST", "Sydney 5pm = 11.30am IST", "Perth 11am = 8.30am IST", "Standard 8.30am to 5.30pm IST"],
        faqs=[("Do we need an Indian entity?",
               "No. An employer of record or our staffing payroll covers the first hires, and we move people across when your entity is ready."),
              ("Does the Fair Work Act cover our India team?",
               "No. Indian employees are covered by Indian employment law: provident fund, gratuity and notice period rather than superannuation and awards."),
              ("Can Indian accountants work in Xero and MYOB?",
               "Many can, particularly those from Australian outsourcing providers in Ahmedabad, Pune and Bengaluru, and we screen for the specific stack."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period at senior levels.")],
        cta_a="Setting up an India team?", cta_b="Start with one good hire.",
        cta_copy="Tell us the role, who it reports to in Australia and the hours you need covered. We will come back with a market read and a plan.",
    ),
}

# ------------------------------------------------- COUNTRY + SERVICE PAGES
SERVICES = {
    "it-recruitment": dict(
        label="IT Recruitment", nav="IT Recruitment", kw="IT recruitment",
        h1_b="Engineering, data and AI hiring in India.",
        lead_tail="We hire the engineers who ship, the platform people who keep it running and the managers who hold a team together.",
        short_tail="We hire software, data and AI roles in India, screen for what the candidate has actually built, and run the loop around your hours.",
        roles=[("Software engineering", "Backend, full-stack, frontend, mobile, engineering manager", "Mid to Director"),
               ("Data engineering", "Data engineers, platform engineers, Snowflake and Databricks specialists, analytics engineers", "Mid to Lead"),
               ("AI &amp; ML", "ML engineers, applied scientists, LLM and RAG engineers, MLOps", "Senior IC to Lead"),
               ("Cloud &amp; DevOps", "DevOps, SRE, cloud architects, platform reliability", "Mid to Lead"),
               ("Quality &amp; release", "QA automation, SDET, release engineering", "Mid to Lead"),
               ("Product &amp; delivery", "Technical product managers, scrum leads, delivery managers", "Mid to Director")],
        method_h="We read the build history, not only the CV.",
        method_lede="Every market has candidates who interview better than they build.",
        method_body="We ask what the candidate owned, what broke and what they did about it, then check the story against repositories and references.",
        faqs=[("How do you screen engineers?",
               "A structured conversation about what they have built and owned, a look at public work where it exists, and reference checks on the specific claims."),
              ("Can you hire a full pod rather than single roles?",
               "Yes. Pod builds of four to ten people run as a dedicated engagement with one recruiter and a weekly pipeline review."),
              ("Which Indian cities are strongest for engineering talent?",
               "Bengaluru for depth, Hyderabad and Pune for retention and cost, Chennai for platform work, Delhi NCR for product-led companies.")],
    ),
    "finance-leadership-hiring": dict(
        label="Finance Leadership Hiring", nav="Finance Leadership", kw="finance leadership hiring",
        h1_b="CFOs, controllers and finance heads.",
        lead_tail="We run confidential, research-led searches for the controller who owns the close, the finance head in the leadership meeting and the CFO the board has to trust.",
        short_tail="We run retained, confidential searches for CFOs, finance directors, controllers and FP&amp;A heads, with a written market map before any shortlist.",
        roles=[("Chief financial officer", "CFO, group CFO, divisional CFO", "CFO"),
               ("Finance leadership", "Finance director, VP finance, head of finance, India finance head", "Director to VP"),
               ("Controllership", "Financial controller, group reporting head, chief accountant", "Manager to Director"),
               ("Planning &amp; analysis", "Head of FP&amp;A, business finance head, commercial finance director", "Senior Manager to Director"),
               ("Treasury &amp; risk", "Treasury head, head of internal audit, risk and compliance lead", "Manager to Director"),
               ("Transformation", "Finance transformation lead, shared services head, ERP programme lead", "Senior Manager to Director")],
        method_h="A market map before a shortlist.",
        method_lede="Senior searches go wrong at the brief, not at the interview.",
        method_body="We write down the realistic universe first: companies, titles, pay and recent moves. Then we search discreetly and present four or five people with written assessments.",
        faqs=[("Is a leadership search retained or contingency?",
               "Senior and confidential hires are retained, with a staged fee; specialist roles below that can run on contingency."),
              ("Can the search stay confidential?",
               "Yes. We approach candidates without naming you until they have signed an NDA."),
              ("Do you assess beyond the interview?",
               "We write an assessment against the brief for each shortlisted candidate and take references on request.")],
    ),
}

COUNTRY_SERVICES = {k: ["it-recruitment", "finance-leadership-hiring"] for k in COUNTRIES}

CS = {
    ("us", "it-recruitment"): dict(
        angle="US engineering leaders hiring in India hit two problems: inflated titles, and a ten-hour gap. We screen for the first and design the role around the second.",
        extra_h="What is different about hiring US-facing engineers",
        extra="Candidates who have worked with American product teams expect a 2pm to 11pm IST day and price it in. For AI and data engineering the market now prices against US-funded startups.",
        faqs=[("Can engineers overlap with US hours?", "A 2pm to 11pm IST day is normal and covers most of the East Coast morning; full overnight shifts narrow the pool and add 15 to 25 percent to cost.")],
    ),
    ("us", "finance-leadership-hiring"): dict(
        angle="The senior India finance hire for a US company is usually a controller who can satisfy the parent's auditors while building a team from nothing.",
        extra_h="What a US parent needs from the first finance leader",
        extra="US GAAP close discipline and the appetite to build with no structure around them rarely sit in one person. We map both pools and tell you which trade-off your brief is making.",
        faqs=[("Do you find candidates with US GAAP and SOX experience?", "Yes. The pool sits mainly in US-headquartered GCCs and Big Four audit practices in Bengaluru, Hyderabad and Gurugram.")],
    ),
    ("uk", "it-recruitment"): dict(
        angle="UK teams get the best of the India time difference: four and a half hours, enough for genuine collaboration rather than handover-only working.",
        extra_h="What is different about hiring UK-facing engineers",
        extra="The overlap lets you run one team rather than two, so we screen for people who speak up on a call with London. Senior data engineering pay in Bengaluru now overlaps with regional UK salaries.",
        faqs=[("Will our India engineers join UK stand-ups?", "Yes. A 12.30pm to 9.30pm IST day covers the full UK working day, and most candidates accept it without a premium.")],
    ),
    ("uk", "finance-leadership-hiring"): dict(
        angle="For UK groups the senior India finance hire usually owns group reporting, the consolidation or the shared service centre.",
        extra_h="What a UK parent needs from the first finance leader",
        extra="IFRS and UK GAAP fluency, a UK statutory audit behind them, and the appetite to build a team. We write down that universe, with current pay, before anyone is approached.",
        faqs=[("Can you find candidates with IFRS and UK statutory reporting experience?", "Yes. It is one of the deeper pools in India, concentrated in UK-parented GCCs and audit practices in Bengaluru, Gurugram and Mumbai.")],
    ),
    ("uae", "it-recruitment"): dict(
        angle="UAE businesses hire engineers either into Dubai and Abu Dhabi or into an India team working Gulf hours, ninety minutes apart.",
        extra_h="What is different about technology hiring for the Gulf",
        extra="For UAE seats the question is whether the candidate will move and at what package; for India seats, whether they can work with a thin local team. Data-residency requirements belong in the brief from day one.",
        faqs=[("Do you place engineers into Dubai or only in India?", "Both. Relocation searches are mostly India to UAE, and we confirm visa status and package expectations before shortlisting.")],
    ),
    ("uae", "finance-leadership-hiring"): dict(
        angle="Gulf finance leadership searches turn on group structure: several entities, several jurisdictions and a shareholder who wants one clean number.",
        extra_h="What a Gulf group needs from a finance leader",
        extra="Consolidation across entities, comfort with thin systems and the judgment to handle a shareholder directly. For relocation candidates the decision is a family one, so we test it before a shortlist exists.",
        faqs=[("Can you run a confidential CFO search in the UAE?", "Yes, and most are. We approach candidates without naming the group until an NDA is signed.")],
    ),
    ("singapore", "it-recruitment"): dict(
        angle="For Singapore businesses an India engineering team is about depth of supply, and the 2.5 hour difference gives you a shared working day.",
        extra_h="What is different about hiring India engineers from Singapore",
        extra="Fintech, trading and payments clients need people who have worked at volume and under audit, so we screen for engineers who can work directly with Singapore product owners.",
        faqs=[("Which Indian cities suit a Singapore-facing engineering team?", "Bengaluru for depth, Hyderabad and Pune for retention and cost, Chennai for platform and payments engineering.")],
    ),
    ("singapore", "finance-leadership-hiring"): dict(
        angle="Singapore-headquartered groups usually hire an India controller or shared services head who owns the close for several countries.",
        extra_h="What a regional CFO needs from the India finance leader",
        extra="Multi-country IFRS reporting, shared service discipline and the stomach to standardise local practice. We map the pool with current pay before any approach.",
        faqs=[("Should the regional controller sit in Singapore or India?", "Singapore if the role needs the regulator and the board in person; India if it owns process and people.")],
    ),
    ("australia", "it-recruitment"): dict(
        angle="Australian teams hire in India for supply, not price. The constraint is the time difference, which works from the Australian afternoon onwards.",
        extra_h="What is different about hiring India engineers from Australia",
        extra="Stand-ups move to the Australian afternoon and the India team owns its own morning, which needs people who can work unsupervised for half a day. Perth clients have almost full overlap.",
        faqs=[("How do stand-ups work with the time difference?", "Most teams move the stand-up to 2pm or later in Sydney, which is 8.30am IST; Perth teams keep their schedule.")],
    ),
    ("australia", "finance-leadership-hiring"): dict(
        angle="For Australian businesses the senior India finance hire is usually an offshore delivery head or a controller running statutory reporting for the parent.",
        extra_h="What an Australian parent needs from the first finance leader",
        extra="IFRS is the shared standard. What matters more is whether the person can run an offshore team at a quality the Australian partners accept without re-reviewing everything.",
        faqs=[("Can you find leaders who have run Australian-facing offshore teams?", "Yes. That pool sits in Ahmedabad, Pune, Bengaluru and Hyderabad, in firms already delivering work for Australian clients.")],
    ),
}

# ------------------------------------------------------ INDIA METRO CITIES
CITIES = {
    "mumbai": dict(
        name="Mumbai", slugpath="/india/mumbai-recruitment-agency",
        kw="recruitment agency in Mumbai",
        h1_b="Finance, analytics and leadership hiring in Mumbai.",
        lead="Banking, insurance, capital markets and most Indian head offices sit within twenty kilometres of each other, and so does the competition for every good finance hire.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent in Mumbai, benchmarked against the banks and head offices competing for the same people.",
        market_h="What the Mumbai market actually looks like.",
        market=["Financial services set the price, and they pay in bonus as well as fixed. A brief benchmarked against a manufacturing band will not land here.",
                "Geography decides acceptance. We ask where people live before we shortlist them.",
                "Ninety-day notice periods and counter-offers are normal, so we stay close to candidates through the whole notice period."],
        sectors=[("Banking, NBFC &amp; capital markets", "Financial controller, product control, treasury, regulatory reporting, risk", "Manager to Director"),
                 ("Insurance &amp; asset management", "Actuarial support, fund accounting, investment reporting, compliance", "Analyst to Head"),
                 ("Conglomerate head offices", "Group reporting, consolidation, FP&amp;A, internal audit, M&amp;A support", "Manager to Director"),
                 ("Media, retail &amp; consumer", "Commercial finance, business partnering, revenue analytics", "Analyst to Senior Manager"),
                 ("Technology &amp; fintech", "Data engineers, analytics leads, ML engineers, platform engineering", "Mid to Head"),
                 ("Leadership", "CFO, finance director, head of FP&amp;A, analytics head", "Director to CFO")],
        hubs=["Bandra Kurla Complex", "Lower Parel", "Worli", "Andheri East", "Powai", "Goregaon", "Navi Mumbai", "Thane"],
        faqs=[("Which roles do you hire for in Mumbai?",
               "Finance and accounting, FP&amp;A, controllership, treasury and risk, analytics and data, AI and ML, and finance leadership up to CFO."),
              ("How long does a Mumbai search take?",
               "Four to six weeks from brief to signed offer for specialist roles, six to ten for leadership, then a 90-day notice period."),
              ("Do you cover Navi Mumbai and Thane?",
               "Yes, as part of the same market, matched on commute."),
              ("Can you benchmark pay for a Mumbai role?",
               "Yes. We benchmark against the specific companies competing for the person, including bonus and retention structures, before the search opens.")],
    ),
    "bangalore": dict(
        name="Bengaluru", alias="Bangalore", slugpath="/india/bangalore-recruitment-agency",
        kw="recruitment agency in Bangalore",
        h1_b="Finance, data and AI hiring in Bengaluru.",
        lead="We are based here, on Infantry Road. Bengaluru has the deepest technology and GCC talent pool in India and the highest churn to match, so the difference between a good hire and a quick exit sits in the screening.",
        short="Stellaspire is a Bengaluru recruitment agency on Infantry Road hiring finance, accounting, analytics, AI and leadership talent for GCCs and growth companies.",
        market_h="What the Bengaluru market actually looks like.",
        market=["GCCs set the benchmark, which keeps pay high and tenure short.",
                "The AI premium is real and still moving, so a band approved a year ago usually needs revisiting.",
                "Commute is a live constraint, so we shortlist on location as well as skill."],
        sectors=[("GCC finance &amp; controllership", "Financial controller, R2R lead, FP&amp;A manager, reporting head", "Manager to Director"),
                 ("Data &amp; analytics", "Analytics manager, data scientist, data engineer, BI lead", "Senior IC to Head"),
                 ("AI &amp; ML", "ML engineer, applied scientist, LLM and platform engineers, MLOps", "Senior IC to Lead"),
                 ("Technology", "Backend, full-stack, DevOps, SRE, engineering manager", "Mid to Director"),
                 ("Startup finance", "Head of finance, controller, revenue and commercial finance", "Manager to Director"),
                 ("Leadership", "Site head, India finance head, analytics head, CFO", "Director to CFO")],
        hubs=["Whitefield", "Outer Ring Road", "Koramangala", "Indiranagar", "Electronic City", "Hebbal", "Bellandur", "Infantry Road and CBD"],
        faqs=[("Where are you based in Bengaluru?",
               "WeWork Prestige Central, 36 Infantry Road, Bengaluru 560001."),
              ("Which roles do you hire for in Bengaluru?",
               "Finance and accounting, FP&amp;A, controllership, analytics and data, AI and ML, technology, and leadership roles up to CFO and site head."),
              ("How fast can you close a Bengaluru role?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period at senior levels."),
              ("Do you hire for startups as well as GCCs?",
               "Yes, and we brief the two differently: startups need builders, GCCs need people who can work with a global parent.")],
    ),
    "delhi-ncr": dict(
        name="Delhi NCR", slugpath="/india/delhi-ncr-recruitment-agency",
        kw="recruitment agency in Delhi NCR",
        h1_b="Hiring across Gurugram, Noida and Delhi.",
        lead="Delhi NCR is three hiring markets that share a metro line: Gurugram for GCCs and consulting, Noida for technology and services, Delhi for head offices and promoter-led businesses.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent across Gurugram, Noida, Greater Noida, Faridabad and Delhi, matched on commute and company type.",
        market_h="What the Delhi NCR market actually looks like.",
        market=["Gurugram is the GCC and consulting belt, with pay benchmarked against global parents.",
                "Noida and Greater Noida are stronger on technology and shared services, at a lower cost base with better retention.",
                "Promoter-led businesses in Delhi hire fast and on working style, and we brief candidates honestly about that."],
        sectors=[("GCC finance &amp; controllership", "Controller, R2R lead, FP&amp;A manager, reporting head", "Manager to Director"),
                 ("Consulting &amp; advisory", "Transaction services, internal audit, risk advisory, finance transformation", "Consultant to Director"),
                 ("Data &amp; analytics", "Analytics manager, data scientist, data engineer, BI lead", "Senior IC to Head"),
                 ("AI &amp; ML", "ML engineers, applied scientists, data platform engineers", "Senior IC to Lead"),
                 ("Corporate &amp; promoter-led", "Group finance, treasury, commercial finance, internal audit", "Manager to Director"),
                 ("Leadership", "CFO, finance director, centre head, analytics head", "Director to CFO")],
        hubs=["Cyber City, Gurugram", "Golf Course Road", "Udyog Vihar", "Noida Sector 62", "Noida Sector 125", "Greater Noida", "Aerocity", "Faridabad"],
        faqs=[("Does NCR mean Gurugram only?",
               "No. We hire across Gurugram, Noida, Greater Noida, Faridabad, Ghaziabad and Delhi, matched on where the office sits."),
              ("Which roles do you hire for in Delhi NCR?",
               "Finance and accounting, FP&amp;A, controllership, consulting and advisory, analytics and data, AI and ML, and leadership roles up to CFO."),
              ("Is Gurugram pay higher than Noida?",
               "Usually, for the same role, so we benchmark by micro-market rather than quoting one NCR number."),
              ("How long does a search take here?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period at senior levels.")],
    ),
    "hyderabad": dict(
        name="Hyderabad", slugpath="/india/hyderabad-recruitment-agency",
        kw="recruitment agency in Hyderabad",
        h1_b="GCC finance, data and AI hiring in Hyderabad.",
        lead="Hyderabad is the default second city for GCCs: strong talent, a cost base below Bengaluru and people who stay longer. The pool thins at the very top.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent in Hyderabad, across the HITEC City and Gachibowli employer set.",
        market_h="What the Hyderabad market actually looks like.",
        market=["Cost and retention are the draw: below Bengaluru on fixed pay, and people stay longer.",
                "The employer set is concentrated in HITEC City, Gachibowli and the Financial District, which makes it easy to benchmark.",
                "Senior supply is thinner, so director-level searches usually run local candidates alongside people returning home from Bengaluru, Chennai or Pune."],
        sectors=[("GCC finance &amp; shared services", "Controller, R2R and P2P leads, FP&amp;A manager, process owners", "Manager to Director"),
                 ("Pharma &amp; life sciences finance", "Plant finance, costing, commercial finance, regulatory reporting", "Analyst to Head"),
                 ("Data &amp; analytics", "Analytics manager, data scientist, data engineer, BI lead", "Senior IC to Head"),
                 ("AI &amp; ML", "ML engineers, applied scientists, platform and MLOps engineers", "Senior IC to Lead"),
                 ("Technology", "Backend, cloud, DevOps, QA automation, engineering manager", "Mid to Director"),
                 ("Leadership", "Site head, finance head, analytics head, shared services director", "Director to VP")],
        hubs=["HITEC City", "Gachibowli", "Financial District", "Madhapur", "Kondapur", "Banjara Hills", "Uppal", "Shamshabad"],
        faqs=[("Why hire in Hyderabad instead of Bengaluru?",
               "Lower cost for the same role and better retention; the trade-off is a thinner pool at director level, which we solve with a relocation search."),
              ("Which roles do you hire for in Hyderabad?",
               "GCC finance and shared services, controllership, FP&amp;A, analytics and data, AI and ML, technology, and leadership roles up to site head."),
              ("Can you find people willing to relocate to Hyderabad?",
               "Yes. Many candidates in Bengaluru and Chennai have family in Telangana or Andhra Pradesh and will move for the right role."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period.")],
    ),
    "pune": dict(
        name="Pune", slugpath="/india/pune-recruitment-agency",
        kw="recruitment agency in Pune",
        h1_b="Finance, analytics and engineering hiring in Pune.",
        lead="Manufacturing head offices, automotive engineering, GCCs in Hinjawadi and Kharadi, and a candidate base that tends to stay put. Pune is where cost-conscious teams go when Bengaluru stops making sense.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent in Pune, across the Hinjawadi and Kharadi GCC belt and the manufacturing corridor.",
        market_h="What the Pune market actually looks like.",
        market=["Two markets in one city: the GCC belt hires like Bengaluru, slightly cheaper, and the manufacturing corridor pays on a different curve.",
                "Retention is the real advantage. Pune candidates move less often than Bengaluru candidates at the same level.",
                "Hinjawadi to Kharadi is a decision, not a detail, so we shortlist on where a candidate lives."],
        sectors=[("GCC finance &amp; shared services", "Controller, R2R lead, FP&amp;A manager, process owners", "Manager to Director"),
                 ("Manufacturing &amp; automotive finance", "Plant finance, costing, commercial finance, capex and project finance", "Analyst to Head"),
                 ("Engineering &amp; technology", "Embedded, backend, cloud, DevOps, engineering manager", "Mid to Director"),
                 ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, data scientist", "Senior IC to Head"),
                 ("Outsourced accounting", "Accounts preparation, bookkeeping leads, workpaper reviewers for UK, US and Australian clients", "Associate to Manager"),
                 ("Leadership", "Finance head, plant CFO, centre head, analytics head", "Director to CFO")],
        hubs=["Hinjawadi", "Kharadi", "Magarpatta", "Baner", "Viman Nagar", "Chakan", "Talegaon", "Pimpri-Chinchwad"],
        faqs=[("Which roles do you hire for in Pune?",
               "GCC finance and shared services, manufacturing and plant finance, FP&amp;A, analytics and data, AI and ML, engineering, and leadership roles."),
              ("Is Pune cheaper than Bengaluru?",
               "For most finance and analytics roles, yes, with better retention; senior supply is thinner, so director-level searches sometimes need relocation candidates."),
              ("Do you cover the manufacturing belt?",
               "Yes. Chakan, Talegaon and Pimpri-Chinchwad plant finance and costing roles are a regular part of our Pune work."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period.")],
    ),
    "chennai": dict(
        name="Chennai", slugpath="/india/chennai-recruitment-agency",
        kw="recruitment agency in Chennai",
        h1_b="Finance, analytics and engineering hiring in Chennai.",
        lead="Chennai hires on depth rather than noise: manufacturing head offices, a large captive finance base along OMR, and engineering talent that stays for years.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent in Chennai, across the OMR captive belt, the manufacturing corridor and the city centre.",
        market_h="What the Chennai market actually looks like.",
        market=["Retention is the best among the big five cities, which suits process-heavy finance and long-cycle engineering work.",
                "The captives along OMR hire most of the finance, analytics and platform talent and benchmark against each other.",
                "Manufacturing finance is a genuine specialism, drawn from the automotive corridor rather than from a GCC."],
        sectors=[("Captive finance &amp; shared services", "Controller, R2R lead, FP&amp;A manager, process owners", "Manager to Director"),
                 ("Manufacturing &amp; automotive finance", "Plant finance, costing, inventory control, capex finance", "Analyst to Head"),
                 ("Banking &amp; insurance operations", "Fund accounting, regulatory reporting, reconciliations, risk analytics", "Analyst to Head"),
                 ("Technology &amp; platform", "Backend, platform, embedded, DevOps, engineering manager", "Mid to Director"),
                 ("Data &amp; analytics", "Analytics manager, data engineer, data scientist, BI lead", "Senior IC to Head"),
                 ("Leadership", "Finance head, plant CFO, centre head, analytics head", "Director to CFO")],
        hubs=["Old Mahabalipuram Road", "Guindy", "Nungambakkam", "Ambattur", "Sriperumbudur", "Oragadam", "Perungudi", "Taramani"],
        faqs=[("Which roles do you hire for in Chennai?",
               "Captive and shared service finance, manufacturing and plant finance, banking and insurance operations, analytics and data, AI and ML, engineering, and leadership roles."),
              ("Is Chennai good for manufacturing finance?",
               "It is one of the strongest markets in India for it, with a deep pool around Sriperumbudur and Oragadam."),
              ("Do candidates here expect to relocate?",
               "Less than in other cities, which helps retention; senior relocation searches usually target people returning home from Bengaluru or the Gulf."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period.")],
    ),
    "ahmedabad": dict(
        name="Ahmedabad", slugpath="/india/ahmedabad-recruitment-agency",
        kw="recruitment agency in Ahmedabad",
        h1_b="Finance, accounting and offshore delivery hiring in Ahmedabad.",
        lead="The best value finance market in India: a deep chartered accountant base, a large offshore accounting industry, and GIFT City pulling in financial services.",
        short="Stellaspire hires finance, accounting, analytics and leadership talent in Ahmedabad and Gandhinagar, including GIFT City, the strongest value market for offshore accounting teams.",
        market_h="What the Ahmedabad market actually looks like.",
        market=["Gujarat produces a large number of CAs and many stay, giving unusual depth in accounting at a cost well below Bengaluru or Mumbai.",
                "Offshore accounting is already an industry here, so candidates arrive fluent in Xero, QuickBooks, Sage and client workpapers.",
                "GIFT City is pulling banking, insurance and fund administration roles into the market and lifting pay for regulated-finance experience."],
        sectors=[("Accounting &amp; controllership", "Financial controller, chief accountant, R2R lead, chartered accountants", "Manager to Director"),
                 ("Offshore accounting delivery", "Accounts preparation, bookkeeping leads, workpaper reviewers, tax support", "Associate to Manager"),
                 ("GIFT City financial services", "Fund accounting, regulatory reporting, compliance, treasury operations", "Analyst to Head"),
                 ("Manufacturing &amp; pharma finance", "Plant finance, costing, commercial finance, exports and trade finance", "Analyst to Head"),
                 ("Data &amp; analytics", "Analytics manager, data engineer, BI lead", "Senior IC to Head"),
                 ("Leadership", "Finance head, delivery head, CFO for a promoter-led group", "Director to CFO")],
        hubs=["GIFT City, Gandhinagar", "Prahlad Nagar", "SG Highway", "Bodakdev", "Ashram Road", "Sanand", "Changodar", "Gandhinagar"],
        faqs=[("Why hire finance roles in Ahmedabad?",
               "Deep chartered accountant supply at a cost well below Bengaluru, Mumbai or Gurugram, with better retention."),
              ("Can you hire offshore accounting teams for UK, US or Australian firms?",
               "Yes. Candidates here routinely work on overseas client books in Xero, QuickBooks and Sage."),
              ("Do you hire for GIFT City?",
               "Yes: fund accounting, regulatory reporting, compliance and treasury roles, usually with a relocation search alongside local candidates."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership; notice periods are often shorter than in Bengaluru or Mumbai.")],
    ),
    "kolkata": dict(
        name="Kolkata", slugpath="/india/kolkata-recruitment-agency",
        kw="recruitment agency in Kolkata",
        h1_b="Finance, accounting and analytics hiring in Kolkata.",
        lead="A strong chartered accountant tradition, an established shared services base in Salt Lake Sector V and New Town, and a cost structure that suits process-heavy finance work.",
        short="Stellaspire hires finance, accounting, analytics and leadership talent in Kolkata, across Salt Lake Sector V, New Town and the central business district.",
        market_h="What the Kolkata market actually looks like.",
        market=["The accounting base is deep and loyal, and candidates stay with an employer for years rather than months.",
                "Shared services sit in Salt Lake Sector V and New Town, with pay benchmarked below Bengaluru and Hyderabad.",
                "Senior searches often run local candidates alongside people returning home from Bengaluru, Mumbai or the Gulf."],
        sectors=[("Accounting &amp; controllership", "Financial controller, chief accountant, R2R lead, chartered and cost accountants", "Manager to Director"),
                 ("Shared services", "P2P and O2C process leads, reconciliations, reporting analysts", "Associate to Manager"),
                 ("Manufacturing &amp; infrastructure finance", "Plant finance, costing, project finance, commercial finance", "Analyst to Head"),
                 ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, reporting analytics", "Senior IC to Head"),
                 ("Technology", "Backend, full-stack, QA, support engineering", "Mid to Lead"),
                 ("Leadership", "Finance head, shared services head, CFO for a regional group", "Director to CFO")],
        hubs=["Salt Lake Sector V", "New Town Rajarhat", "Park Street", "Camac Street", "Bantala", "Howrah", "Dankuni", "Taratala"],
        faqs=[("Which roles do you hire for in Kolkata?",
               "Accounting and controllership, shared service process roles, manufacturing and infrastructure finance, analytics and data, technology, and finance leadership."),
              ("Is Kolkata a good location for a shared service centre?",
               "For process-heavy finance work, yes: cost sits below Bengaluru and Hyderabad, retention is better and accounting supply is strong."),
              ("Can you find senior finance leaders in Kolkata?",
               "Yes, usually by running local candidates alongside people willing to return from Bengaluru, Mumbai or the Gulf."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period.")],
    ),
}

# ------------------------------- American spelling pass for the /us pages
SPELL_US = [
    ("organisation", "organization"), ("Organisation", "Organization"),
    ("organise", "organize"),
    # stems only, never "specialist" -- that word is identical in both spellings
    ("specialise", "specialize"), ("specialising", "specializing"), ("specialised", "specialized"),
    ("Specialise", "Specialize"), ("Specialised", "Specialized"),
    ("recognise", "recognize"), ("recognised", "recognized"),
    ("prioritise", "prioritize"), ("standardise", "standardize"), ("standardised", "standardized"),
    ("stabilise", "stabilize"), ("stabilisation", "stabilization"),
    ("utilise", "utilize"), ("analyse", "analyze"), ("analysed", "analyzed"),
    ("centre", "center"), ("Centre", "Center"), ("programme", "program"),
    ("labour", "labor"), ("behaviour", "behavior"), ("favour", "favor"),
    ("licence", "license"), ("modelling", "modeling"), ("fulfil ", "fulfill "),
    ("whilst", "while"), ("judgement", "judgment"), ("practise", "practice"),
    ("CVs", "resumes"), ("CV", "resume"),
]
