"""Content for the global, country and India-city pages.

Every page's copy lives here as data; build_geo.py turns it into
<slug>.body.html files and the built embeds in out/.

Wording follows the market each page is written for: US pages use
American spelling and American hiring vocabulary (resume, W-2, EOR,
US GAAP), UK pages use CV and IR35, UAE pages use Emiratisation and
MOHRE, Singapore pages use MOM passes and CPF, Australia pages use
superannuation and Fair Work. SPELL_US at the bottom catches shared
boilerplate on the American pages.
"""

# ---------------------------------------------------------------- COUNTRIES
COUNTRIES = {
    "us": dict(
        name="the US", formal="the United States", lang="en-US", spell="us",
        path="/us", currency="USD", nav="United States",
        kw="India recruitment agency for US companies",
        eyebrow="Hiring in India from the United States",
        h1_a="India recruitment for US companies.",
        h1_b="Finance, data and AI teams in Bengaluru.",
        lead="American companies hire in India for two reasons: the talent is deep, and the day starts while New York sleeps. Stellaspire runs the search end to end, from the first controller to a forty-person analytics team, and hands you a shortlist you can actually interview.",
        short="Stellaspire is a women-led search firm in Bengaluru. We hire finance, accounting, analytics and AI talent in India for US companies, run every interview loop around your time zone, and tell you what the role really pays in the city you are hiring in.",
        why_h="What US teams come to us for.",
        why_body="Most of our American clients are not opening a captive center on day one. They need three good people in India, quickly, and nobody in-house who can read an Indian resume. That is the gap we sit in.",
        why_items=[
            ("US-headquartered companies hiring their first India team", "a controller, an FP&amp;A lead or two data engineers, before there is an India HR function."),
            ("CFOs moving record-to-report or planning work offshore", "people who have run US GAAP close cycles and can talk to your auditors."),
            ("Series B to pre-IPO companies", "finance and data hires who have been through a US audit, a SOX readiness exercise or an S-1."),
            ("GCC leaders scaling a center", "the next layer of managers once the first twenty seats are full."),
        ],
        roles=[("Finance &amp; accounting", "Controller, record-to-report lead, US GAAP reporting manager, AR and AP leads", "Manager to Director"),
               ("FP&amp;A", "FP&amp;A manager, business finance partner, revenue analyst", "Analyst to Senior Manager"),
               ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, data scientist", "Senior IC to Head"),
               ("AI &amp; ML", "ML engineer, applied scientist, LLM and platform engineers", "Senior IC to Lead"),
               ("Technology", "Backend, full-stack, DevOps, QA automation, engineering manager", "Mid to Director"),
               ("Leadership", "India site head, country finance head, center director", "Director to VP")],
        method_h="A shortlist you can take straight into a loop.",
        method_lede="Four or five names, each with a note on why they fit and what they will cost you.",
        method_body="We interview before you do. Every profile carries the candidate's current compensation in INR, their notice period, the reason they are moving and how their experience maps onto US reporting standards. If someone is wrong for the role we say so rather than padding the list.",
        comp_h="Payroll, entity and the paperwork.",
        comp_lede="You do not need an Indian entity to make the first hire.",
        comp_cards=[("No entity yet", "Employer of record", "Most first hires go on an EOR or a staffing payroll while the entity is set up. We work with whichever provider you choose and write offers that transfer cleanly later."),
                    ("Scaling up", "Your own India entity", "Once you have a private limited company and a payroll provider, we hire onto your books. Offers follow Indian statutory norms: provident fund, gratuity, notice period and the retention structures that are market here."),
                    ("Either way", "Contract and IP", "We flag the clauses US counsel usually asks about: assignment of IP, the limits of non-solicit under Indian law, and what a 90-day notice period does to your start date.")],
        tz_h="The overlap problem, solved in the offer.",
        tz_body="India is 9.5 to 12.5 hours ahead of the US mainland. Candidates who have worked with American teams know what that costs them, so we raise it in the first conversation rather than at offer stage. Most finance and analytics hires settle on a 2pm to 11pm IST day with a hard stop; engineering usually needs less overlap. We tell you which candidates will take a 7am Eastern stand-up and which will not.",
        tz_chips=["Eastern 8:30am = 6pm IST", "Central 8am = 6:30pm IST", "Pacific 7am = 7:30pm IST", "Hybrid 2pm to 11pm IST"],
        faqs=[("Can you hire in India if we have no Indian entity?",
               "Yes. Most US clients make their first two or three hires through an employer of record or our staffing payroll, then move people onto their own entity later. We write the offer so the transfer does not reset tenure or benefits."),
              ("How long does a search take?",
               "A specialist finance or data role in Bengaluru or Hyderabad usually takes four to six weeks from brief to signed offer, plus the candidate's notice period, which is commonly 60 to 90 days in India. Leadership searches run six to ten weeks."),
              ("Will candidates work US hours?",
               "Many will, within limits. Finance and analytics candidates routinely take a 2pm to 11pm IST shift. Full overnight shifts narrow the pool sharply and cost 15 to 25 percent more, so we would rather design the role around a real overlap window."),
              ("How do India salaries compare with US salaries?",
               "Lower, though not uniformly, and the gap has narrowed quickly for AI, data engineering and controllership. We benchmark every role against the specific city and the companies you would be hiring from, and share the range before you approve the brief."),
              ("Do you verify candidates before we see them?",
               "Yes. We check employment history, education and reason for leaving, and talk through compensation documents. Formal background screening runs through your provider or ours once an offer is accepted."),
              ("What are your fees?",
               "A percentage of annual fixed pay for contingency search, a staged fee for retained leadership search, and a monthly rate for dedicated team hiring. Commercial and replacement terms go to you in writing before we start.")],
        cta_a="Hiring in India this quarter?", cta_b="Let's scope it.",
        cta_copy="Send us the role, the reporting line and the time-zone expectation. You will get a market read and a suggested approach, not a deck.",
    ),
    "uk": dict(
        name="the UK", formal="the United Kingdom", lang="en-GB", spell="gb",
        path="/uk", currency="GBP", nav="United Kingdom",
        kw="India recruitment agency for UK companies",
        eyebrow="Hiring in India from the United Kingdom",
        h1_a="India recruitment for UK companies.",
        h1_b="Finance, analytics and AI hires that stay.",
        lead="British companies have been hiring in India for thirty years, which means the easy talent has been hired several times over. Stellaspire works the harder end: qualified accountants, FP&amp;A managers, analytics leads and AI engineers who will still be there after the first appraisal cycle.",
        short="Stellaspire is a women-led search firm in Bengaluru. We hire finance, accounting, analytics and AI talent in India for UK companies, work a 4.5 to 5.5 hour difference that suits both sides, and benchmark pay against the GCCs you are competing with.",
        why_h="Where UK clients usually need us.",
        why_body="The problem is rarely sourcing. It is that a London hiring manager cannot tell a strong Indian CV from a well-written one, and the agencies they have used send fifty of both.",
        why_items=[
            ("UK groups setting up a shared service centre", "a finance manager and a controller first, then the team underneath them."),
            ("Finance directors consolidating group reporting", "people fluent in IFRS and UK GAAP who have closed books for a UK parent."),
            ("Scale-ups and PE-backed businesses", "a small senior India team rather than a large junior one."),
            ("Heads of data", "analytics and engineering hires who can hold their own with the UK business, not only build the pipeline."),
        ],
        roles=[("Finance &amp; accounting", "Financial controller, group reporting manager, R2R lead, qualified accountants (ACA, ACCA, CIMA, CA)", "Manager to Director"),
               ("FP&amp;A", "FP&amp;A manager, commercial finance partner, management accountant", "Analyst to Senior Manager"),
               ("Data &amp; analytics", "Analytics lead, data engineer, BI manager, data scientist", "Senior IC to Head"),
               ("AI &amp; ML", "ML engineer, applied scientist, MLOps", "Senior IC to Lead"),
               ("Risk &amp; compliance", "Internal audit, financial crime, regulatory reporting", "Manager to Director"),
               ("Leadership", "India centre head, finance head, delivery director", "Director to VP")],
        method_h="Six CVs, each one worth reading.",
        method_lede="We would rather send four strong profiles late than twenty on Friday.",
        method_body="Each CV arrives with a written note: current and expected pay in INR, notice period, what the candidate actually owns today and where they are weak. We interview everyone ourselves, and when a brief is priced below the market we say so rather than running a search we expect to lose.",
        comp_h="Entity, payroll and the compliance questions.",
        comp_lede="UK finance teams ask the same four questions, so here they are answered.",
        comp_cards=[("Before the entity", "Employer of record", "Early hires often sit with an EOR while the Indian subsidiary is incorporated. Offers are drafted so that moving onto your own payroll is administrative rather than a renegotiation."),
                    ("On your books", "Indian statutory pay", "Provident fund, gratuity, leave encashment and a standard 30 to 90 day notice period. None of this resembles an IR35 question: these are permanent employees of an Indian company."),
                    ("Where it applies", "Contractors", "If you engage an Indian professional as a contractor, the test is Indian employment law, not IR35. We will tell you when a role is better off as a permanent hire.")],
        tz_h="Four and a half hours is the whole advantage.",
        tz_body="India is 5.5 hours ahead of the UK in winter and 4.5 in summer. A 10am London stand-up is mid-afternoon in Bengaluru, which is why UK and India teams work better together than UK and US ones. Most candidates we place work 12.30pm to 9.30pm IST with real overlap from lunchtime onwards. The pattern goes in the brief so nobody discovers it at offer stage.",
        tz_chips=["London 9am = 2.30pm IST", "London 1pm = 6.30pm IST", "BST: 4.5 hours", "GMT: 5.5 hours"],
        faqs=[("Do we need an Indian entity to hire?",
               "No. An employer of record covers the first few hires. Once you have an Indian private limited company and a payroll provider, we hire directly onto your books."),
              ("How long is a search, start to finish?",
               "Four to six weeks to a signed offer for specialist finance and data roles, six to ten for leadership. Add the notice period, commonly 60 to 90 days in India for senior staff."),
              ("Which Indian qualifications map onto ACA or ACCA?",
               "Chartered Accountant (ICAI) is the closest equivalent and the qualification most of our finance shortlists carry. Many candidates also hold ACCA or CIMA, and a smaller number are US CPAs. We note the mix on every shortlist."),
              ("Does IR35 apply to our India hires?",
               "No. IR35 is a UK tax rule. Indian employees are employed under Indian law by your entity or by an employer of record, and contractor arrangements in India are tested against Indian rules instead."),
              ("What does a finance manager in Bengaluru cost compared with Manchester?",
               "Substantially less, though the gap is smaller than most UK boards expect at controller level and above. We benchmark against the specific GCCs and Indian corporates competing for the same person and share the range before the search opens."),
              ("Can you run a confidential search?",
               "Yes. Leadership and replacement hires are usually retained and run without naming you until the candidate has signed an NDA.")],
        cta_a="Building an India team?", cta_b="Start with the brief.",
        cta_copy="Tell us the role, who it reports to in the UK and the pay range you have approved. We will come back on whether it is winnable and how we would run it.",
    ),
    "uae": dict(
        name="the UAE", formal="the United Arab Emirates", lang="en-AE", spell="gb",
        path="/uae", currency="AED", nav="UAE",
        kw="recruitment agency for UAE companies",
        eyebrow="Hiring from the UAE",
        h1_a="Recruitment for UAE companies.",
        h1_b="Finance hires for Dubai and Abu Dhabi, and India back-office teams.",
        lead="Half the finance market in Dubai is already Indian, which cuts both ways: the talent pool is familiar, and so is the competition for it. Stellaspire hires finance, accounting, analytics and AI people for UAE businesses, whether the seat is in Dubai, Abu Dhabi or a back office in Bengaluru.",
        short="Stellaspire is a women-led search firm in Bengaluru. We hire finance, accounting, analytics and AI talent for UAE companies, source India-based candidates for relocation to Dubai and Abu Dhabi, and staff India back offices for Gulf groups. Same business week, ninety minutes apart.",
        why_h="Two kinds of UAE mandate.",
        why_body="Either you are hiring someone into the Emirates, usually from India, or you are putting a finance and analytics team in India to support the Gulf business. We run both, and the search looks quite different.",
        why_items=[
            ("Family groups and holding companies", "a group financial controller or an FP&amp;A head who has worked across several entities and jurisdictions."),
            ("DIFC and ADGM regulated firms", "finance, risk and compliance hires who understand the regulator and the reporting that comes with it."),
            ("Contracting, retail and logistics groups", "cost controllers, project accountants and consolidation specialists who can work with thin systems."),
            ("UAE businesses building an India back office", "an India shared service team for accounting, reporting and analytics, run on Gulf working hours."),
        ],
        roles=[("Group finance", "Group financial controller, consolidation manager, finance manager, chief accountant", "Manager to Director"),
               ("FP&amp;A &amp; commercial", "FP&amp;A head, budgeting manager, cost controller, commercial analyst", "Analyst to Head"),
               ("Treasury &amp; risk", "Treasury manager, credit control head, internal audit, compliance officer", "Manager to Director"),
               ("Data &amp; analytics", "Analytics manager, BI lead, data engineer", "Senior IC to Head"),
               ("AI &amp; technology", "ML engineer, data platform engineer, ERP and systems leads", "Senior IC to Lead"),
               ("Leadership", "CFO, finance director, India centre head for a Gulf group", "Director to CFO")],
        method_h="Candidates who will actually move, at a number that works.",
        method_lede="A Gulf offer is a family decision, and that is where most failed searches fail.",
        method_body="For relocation hires we test the real question early: schooling, spouse employment, the all-in package against what they keep in India today, and whether they have lived in the Gulf before. For India-based hires we benchmark against the GCCs in the same city. Either way, the shortlist carries each candidate's current package in writing.",
        comp_h="Visas, Emiratisation and the package.",
        comp_lede="The compliance layer is yours, but we will not send you candidates who break it.",
        comp_cards=[("Mainland and free zone", "Work permits and visas", "Employment visas are sponsored by your entity through MOHRE, or by the free zone authority in DIFC, ADGM, DMCC and others. We confirm each candidate's current visa status and availability before shortlisting."),
                    ("Where they apply", "Emiratisation targets", "Mainland companies above the skilled-worker threshold carry Emiratisation quotas. If a seat is earmarked for an Emirati national, say so at the brief and we will run that search separately rather than mixing the pools."),
                    ("Every offer", "Package, not salary", "Basic, housing, schooling, flights, end-of-service gratuity, and whether the role is DIFC or mainland. We present offers the way candidates compare them: an all-in annual AED figure against their current net position.")],
        tz_h="Same week, ninety minutes apart.",
        tz_body="India is 1.5 hours ahead of the UAE and both run a Monday to Friday week, so an India team supporting a Dubai business is effectively inside the same working day. That is why Gulf groups have moved so much accounting and reporting work to Bengaluru, Hyderabad and Pune. For relocation hires it also means candidates can interview in person over a weekend.",
        tz_chips=["Dubai 9am = 10.30am IST", "Dubai 5pm = 6.30pm IST", "Monday to Friday both sides", "Direct flights, three hours"],
        faqs=[("Do you place candidates inside the UAE or only in India?",
               "Both. We source India-based candidates for relocation to Dubai, Abu Dhabi and Sharjah, and we build India-based finance and analytics teams for UAE groups. The brief decides which."),
              ("Can you help with the employment visa?",
               "The visa is sponsored by your entity or free zone, so the filing sits with you or your PRO. We confirm every candidate's current status, notice period and documentation so there is no surprise at offer stage."),
              ("How do you handle Emiratisation quotas?",
               "If a role is reserved for an Emirati national we run it as a separate search with a different sourcing approach. Mixing a quota role into an expatriate shortlist wastes everyone's time."),
              ("What does a group financial controller in Dubai expect to be paid?",
               "It depends on group size, number of entities and whether the role is DIFC or mainland, and candidates compare all-in packages rather than basic pay. We share a benchmarked range for your brief before the search opens."),
              ("Which Indian qualifications do UAE employers recognise?",
               "Chartered Accountant (ICAI) is the most common on our shortlists, followed by ACCA and CPA. For DIFC and ADGM regulated roles we note regulatory reporting experience alongside the qualification."),
              ("How quickly can someone start?",
               "Notice periods in India run 30 to 90 days, and visa processing adds two to six weeks depending on the emirate and free zone. Plan on eight to twelve weeks from signed offer to first day in the Gulf.")],
        cta_a="Hiring for Dubai, Abu Dhabi or an India back office?", cta_b="Tell us which.",
        cta_copy="Send the role, the entity it sits in and the package band. We will tell you what the market looks like and how we would run the search.",
    ),
    "singapore": dict(
        name="Singapore", formal="Singapore", lang="en-SG", spell="gb",
        path="/singapore", currency="SGD", nav="Singapore",
        kw="recruitment agency for Singapore companies",
        eyebrow="Hiring from Singapore",
        h1_a="Recruitment for Singapore companies.",
        h1_b="India teams, and regional finance hires.",
        lead="Singapore is where the regional CFO sits and India is where the team gets built. Stellaspire hires finance, accounting, analytics and AI talent in India for Singapore-headquartered businesses, and runs regional searches where the role is better filled from the Indian market.",
        short="Stellaspire is a women-led search firm in Bengaluru. We hire finance, accounting, analytics and AI talent in India for Singapore companies, work a 2.5 hour difference with a full shared afternoon, and benchmark pay against the GCCs hiring in the same cities.",
        why_h="Why Singapore teams hire in India.",
        why_body="A Singapore head office rarely has the headcount budget for a full regional finance team, and local hiring is tight. India gives depth at a cost that works, provided somebody senior is doing the filtering.",
        why_items=[
            ("Regional CFOs and finance directors", "a controller, a consolidation manager and an FP&amp;A team in India reporting into Singapore."),
            ("Businesses weighing local versus offshore", "roles that genuinely belong offshore rather than being contested under the Fair Consideration Framework."),
            ("Fintech, trading and commodity firms", "product control, treasury operations and regulatory reporting talent with the volume to practise on."),
            ("Heads of data and engineering", "analytics and AI hires in Bengaluru or Hyderabad who can work a full Singapore day."),
        ],
        roles=[("Finance &amp; accounting", "Financial controller, consolidation manager, R2R lead, chartered accountants", "Manager to Director"),
               ("FP&amp;A", "FP&amp;A manager, regional business partner, management reporting lead", "Analyst to Senior Manager"),
               ("Treasury &amp; product control", "Treasury operations, product control, reconciliations, regulatory reporting", "Analyst to Head"),
               ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, data scientist", "Senior IC to Head"),
               ("AI &amp; ML", "ML engineer, applied scientist, data platform engineer", "Senior IC to Lead"),
               ("Leadership", "India site head, regional finance head, shared services director", "Director to VP")],
        method_h="One recruiter, from brief to joining day.",
        method_lede="You will not be handed to an account manager after the kick-off call.",
        method_body="The person who takes your brief runs the search, interviews the candidates and stays on the offer. Shortlists carry current pay in INR, notice period, the reason for the move and an honest note on the gaps. Where we think the brief is unwinnable at the approved band, we say so in week one.",
        comp_h="Employment, payroll and the rules that matter.",
        comp_lede="Two sets of rules: Singapore's for passes, India's for employment.",
        comp_cards=[("Hiring into Singapore", "Employment Pass and S Pass", "If the seat is in Singapore, the pass framework and the Fair Consideration Framework advertisement sit with your HR team. We will tell you plainly when a role is unlikely to clear the qualifying salary and belongs in India instead."),
                    ("Most common", "India hiring, no entity needed", "Early India hires go through an employer of record or our payroll. CPF has no Indian equivalent: the statutory items are provident fund and gratuity, and we draft offers that reflect them."),
                    ("Scaling", "Shared services build-out", "For a full India shared service centre we hire in waves: leadership first, then process owners, then the analyst layer, against a plan agreed with Singapore finance.")],
        tz_h="A full working afternoon in common.",
        tz_body="Singapore is 2.5 hours ahead of India, so a 9am Singapore meeting is 6.30am in Bengaluru and a 6pm Singapore call is 3.30pm. Most teams settle on an 11am to 8pm IST day, which covers the whole Singapore afternoon. For month-end close this matters more than anything else in the brief, so we design the shift pattern before the search opens.",
        tz_chips=["SG 9am = 6.30am IST", "SG 2pm = 11.30am IST", "SG 6pm = 3.30pm IST", "Hybrid 11am to 8pm IST"],
        faqs=[("Can you hire in India without setting up an entity?",
               "Yes. An employer of record or our staffing payroll covers the first hires, and we move people onto your Indian entity when it is ready."),
              ("Should this role be in Singapore or in India?",
               "If it needs a local licence, a client-facing presence or a regulator relationship, Singapore. If it is reporting, analysis, controllership or engineering, India will usually give you a more experienced person for the same cost. We will give you a straight answer on your brief."),
              ("Does the Fair Consideration Framework affect India hiring?",
               "Not for roles based in India, which are Indian employment. It applies to seats in Singapore, where the advertising and pass requirements sit with your HR team."),
              ("What is the equivalent of CPF in India?",
               "Provident fund, plus gratuity after five years of service. Both are statutory and both appear in the cost-to-company figure we quote on every shortlist."),
              ("How long does a search take?",
               "Four to six weeks from brief to signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day Indian notice period for senior staff."),
              ("Do you cover roles outside finance and data?",
               "We go as far as our knowledge does: finance, accounting, FP&amp;A, analytics, AI and the engineering roles around them. For anything outside that we would rather refer you on than run a search we cannot judge.")],
        cta_a="Planning an India team from Singapore?", cta_b="Let's map it.",
        cta_copy="Share the role, the Singapore reporting line and the shift expectation. We will come back with a market read and an approach.",
    ),
    "australia": dict(
        name="Australia", formal="Australia", lang="en-AU", spell="gb",
        path="/australia", currency="AUD", nav="Australia",
        kw="recruitment agency for Australian companies",
        eyebrow="Hiring from Australia",
        h1_a="Recruitment for Australian companies.",
        h1_b="India finance, analytics and AI teams.",
        lead="Australian businesses have run out of local accountants and data people, and the India option has stopped being purely a cost play. Stellaspire hires finance, accounting, analytics and AI talent in India for Australian companies, with a working day that lines up better than most clients expect.",
        short="Stellaspire is a women-led search firm in Bengaluru. We hire finance, accounting, analytics and AI talent in India for Australian companies, work a 4.5 to 5.5 hour difference, and benchmark pay against the GCCs competing for the same candidates.",
        why_h="What Australian clients are solving for.",
        why_body="The shortage at home is real, particularly in accounting and data engineering. The risk is hiring an India team that needs more supervision than it saves, which is a hiring problem rather than an offshoring one.",
        why_items=[
            ("Accounting and advisory firms", "qualified accountants and bookkeeping teams in India who can work in Xero, MYOB and the client's workpapers."),
            ("CFOs of listed and PE-backed businesses", "controllership and statutory reporting hires familiar with IFRS, which is also the Australian standard."),
            ("Mining, construction and logistics groups", "cost controllers, project accountants and reporting analysts used to operational data."),
            ("Heads of data and product", "analytics, data engineering and ML hires in Bengaluru, Hyderabad or Pune."),
        ],
        roles=[("Finance &amp; accounting", "Financial controller, statutory reporting manager, R2R lead, chartered accountants", "Manager to Director"),
               ("Outsourced accounting", "Accounts preparation, bookkeeping leads, tax support, workpaper reviewers", "Associate to Manager"),
               ("FP&amp;A", "FP&amp;A manager, commercial analyst, budgeting and forecasting lead", "Analyst to Senior Manager"),
               ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, data scientist", "Senior IC to Head"),
               ("AI &amp; ML", "ML engineer, applied scientist, MLOps", "Senior IC to Lead"),
               ("Leadership", "India site head, offshore delivery head, finance head", "Director to VP")],
        method_h="Hire the supervisor before the team.",
        method_lede="Offshore teams fail when the only senior person is in Australia.",
        method_body="We push most clients to hire a manager in India first and build underneath them. It costs more in month one and saves the whole experiment. Shortlists carry current pay in INR, notice period, the systems the candidate has actually used and a note on where they will need support.",
        comp_h="Employment, payroll and the compliance questions.",
        comp_lede="Your India hires are employed under Indian law, not the Fair Work Act.",
        comp_cards=[("No India entity", "Employer of record", "Early hires sit on an EOR or our payroll. Offers are written so that moving onto your own Indian entity later changes nothing for the employee."),
                    ("What replaces super", "Indian statutory items", "There is no superannuation in India. The statutory equivalents are provident fund and gratuity, and notice periods of 30 to 90 days are normal. Awards, penalty rates and Fair Work obligations do not apply to Indian employees."),
                    ("Professional services", "Data and client confidentiality", "Accounting and advisory firms usually need client-data terms, access controls and a confidentiality undertaking per candidate. We raise it at the brief so it is not a late surprise.")],
        tz_h="Mornings in Sydney, afternoons in Bengaluru.",
        tz_body="India is 4.5 to 5.5 hours behind eastern Australia depending on daylight saving, and 2.5 to 3.5 behind Perth. A 9am Sydney stand-up is 3.30am IST, which does not work; a 2pm Sydney call is 8.30am IST, which does. Most teams run 8.30am to 5.30pm IST and keep the Australian afternoon for shared work. We set the pattern in the brief.",
        tz_chips=["Sydney 2pm = 8.30am IST", "Sydney 5pm = 11.30am IST", "Perth 11am = 8.30am IST", "Standard 8.30am to 5.30pm IST"],
        faqs=[("Do we need an Indian entity?",
               "No. An employer of record or our staffing payroll covers the first hires, and we move people across when your entity is ready."),
              ("Does the Fair Work Act cover our India team?",
               "No. Indian employees are covered by Indian employment law. The statutory items are provident fund, gratuity and notice period rather than superannuation and award conditions."),
              ("Can Indian accountants work in Xero and MYOB?",
               "Many can, particularly those who have worked for Australian outsourcing providers in Ahmedabad, Pune and Bengaluru. We screen for the specific stack and for workpaper review experience rather than taking it on trust."),
              ("What about the time difference?",
               "It works in one direction. The Australian afternoon is the Indian morning, so stand-ups move to 2pm or later in Sydney and Melbourne. Perth overlaps almost fully."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus the Indian notice period of 60 to 90 days at senior levels."),
              ("Do you only hire in Bengaluru?",
               "We are based in Bengaluru and hire across Hyderabad, Pune, Mumbai, Delhi NCR, Chennai, Ahmedabad and Kolkata. For outsourced accounting work, Ahmedabad and Pune are often better value than Bengaluru.")],
        cta_a="Setting up an India team?", cta_b="Start with one good hire.",
        cta_copy="Tell us the role, who it reports to in Australia and the hours you need covered. We will come back with a market read and a plan.",
    ),
}

# ------------------------------------------------- COUNTRY + SERVICE PAGES
SERVICES = {
    "it-recruitment": dict(
        label="IT Recruitment", nav="IT Recruitment", kw="IT recruitment",
        h1_b="Engineering, data and AI hiring in India.",
        lead_tail="Stellaspire hires software, data and AI people in India: the engineers who ship, the platform people who keep it running and the managers who hold a team together.",
        short_tail="We hire software engineering, data and AI roles in India, screen for what the candidate has actually built, and run the loop around your working hours.",
        roles=[("Software engineering", "Backend, full-stack, frontend, mobile, engineering manager", "Mid to Director"),
               ("Data engineering", "Data engineers, platform engineers, Snowflake and Databricks specialists, analytics engineers", "Mid to Lead"),
               ("AI &amp; ML", "ML engineers, applied scientists, LLM and RAG engineers, MLOps", "Senior IC to Lead"),
               ("Cloud &amp; DevOps", "DevOps, SRE, cloud architects, platform reliability", "Mid to Lead"),
               ("Quality &amp; release", "QA automation, SDET, release engineering", "Mid to Lead"),
               ("Product &amp; delivery", "Technical product managers, scrum leads, delivery managers", "Mid to Director")],
        method_h="We read the build history, not only the CV.",
        method_lede="Every engineering market has candidates who interview better than they build.",
        method_body="We ask what the candidate owned, what broke and what they did about it, then check the story against their repositories and references. Profiles carry current pay in INR, notice period and a note on the stack they are genuinely strong in rather than the one listed at the top of the page.",
        faqs=[("How do you screen engineers?",
               "A structured conversation about what they have built and owned, a look at public repositories or portfolio work where it exists, and reference checks on the specific claims. Your technical interview still decides; our job is to make sure it is not wasted."),
              ("Can you hire a full pod rather than single roles?",
               "Yes. Pod builds of four to ten people run as a dedicated engagement with one recruiter, a shared hiring plan and a weekly pipeline review."),
              ("Which Indian cities are strongest for engineering talent?",
               "Bengaluru first for depth, Hyderabad and Pune close behind and often better on retention and cost, Chennai strong for platform and embedded work, Delhi NCR good for product-led companies.")],
    ),
    "finance-leadership-hiring": dict(
        label="Finance Leadership Hiring", nav="Finance Leadership", kw="finance leadership hiring",
        h1_b="CFOs, controllers and finance heads.",
        lead_tail="Stellaspire runs confidential, research-led searches for senior finance roles: the controller who owns the close, the finance head who sits in the leadership meeting, the CFO the board has to trust.",
        short_tail="We run retained, confidential searches for CFOs, finance directors, controllers and FP&amp;A heads, with a written market map before any shortlist.",
        roles=[("Chief financial officer", "CFO, group CFO, divisional CFO", "CFO"),
               ("Finance leadership", "Finance director, VP finance, head of finance, India finance head", "Director to VP"),
               ("Controllership", "Financial controller, group reporting head, chief accountant", "Manager to Director"),
               ("Planning &amp; analysis", "Head of FP&amp;A, business finance head, commercial finance director", "Senior Manager to Director"),
               ("Treasury &amp; risk", "Treasury head, head of internal audit, risk and compliance lead", "Manager to Director"),
               ("Transformation", "Finance transformation lead, shared services head, ERP programme lead", "Senior Manager to Director")],
        method_h="A market map before a shortlist.",
        method_lede="Senior searches go wrong at the brief, not at the interview.",
        method_body="We start by writing down the realistic universe: the companies, the titles, what they pay and who has moved recently. You see that before any approach is made. Then we run the search discreetly, interview everyone ourselves and present four or five people with written assessments against the brief.",
        faqs=[("Is a leadership search retained or contingency?",
               "Senior and confidential hires are retained, with a staged fee tied to the market map, the shortlist and the placement. Specialist roles below that can run on contingency."),
              ("Can the search stay confidential?",
               "Yes. We approach candidates without naming you until they have signed an NDA, which matters when the incumbent is still in the seat."),
              ("Do you assess beyond the interview?",
               "We write an assessment against the brief for each shortlisted candidate, take references on request, and will coordinate psychometric or case assessments if your board wants them.")],
    ),
}

COUNTRY_SERVICES = {k: ["it-recruitment", "finance-leadership-hiring"] for k in COUNTRIES}

CS = {
    ("us", "it-recruitment"): dict(
        angle="US engineering leaders hiring in India hit the same two problems: a resume market full of inflated titles, and a ten-hour gap that kills pair programming. We screen for the first and design the role around the second.",
        extra_h="What is different about hiring US-facing engineers",
        extra="Overlap decides the shortlist. Candidates who have worked with American product teams expect a 2pm to 11pm IST day and price it in; those who have not will take the offer and leave within six months. We ask the question on the first call. For AI and data engineering the India market now prices against US-funded startups, so a band set two years ago will not win.",
        faqs=[("Can engineers overlap with US hours?", "A 2pm to 11pm IST day is normal and gives you most of the East Coast morning. Full overnight shifts are available but narrow the pool and add 15 to 25 percent to cost.")],
    ),
    ("us", "finance-leadership-hiring"): dict(
        angle="For US companies the senior India finance hire is usually a controller or an India finance head who can satisfy a US parent's auditors while building a local team from nothing.",
        extra_h="What a US parent needs from the first finance leader",
        extra="Two things that rarely sit in the same person: US GAAP close discipline, and the appetite to build an Indian team with no structure around them. We map both. Candidates out of US-headquartered GCCs are the obvious pool and they are expensive; candidates from Indian corporates cost less and need more support on reporting standards. We will tell you which trade-off your brief is actually making.",
        faqs=[("Do you find candidates with US GAAP and SOX experience?", "Yes. The pool sits mainly in US-headquartered GCCs and the Big Four audit practices in Bengaluru, Hyderabad and Gurugram. We name the realistic universe in the market map before any approach.")],
    ),
    ("uk", "it-recruitment"): dict(
        angle="UK engineering teams get the best of the India time difference, four and a half hours, which makes genuine collaboration possible rather than handover-only working.",
        extra_h="What is different about hiring UK-facing engineers",
        extra="The overlap is good enough to run one team rather than two, which raises the bar on communication. We screen for people who will speak up on a call with London rather than wait to be asked. Pay in Bengaluru for senior data engineering now overlaps with regional UK salaries, so the case for hiring in India is depth of supply as much as cost.",
        faqs=[("Will our India engineers join UK stand-ups?", "Yes. A 12.30pm to 9.30pm IST day covers the full UK working day, and most candidates accept it without a premium.")],
    ),
    ("uk", "finance-leadership-hiring"): dict(
        angle="For UK groups the senior India finance hire usually owns group reporting, the consolidation or the shared service centre, reporting into a UK finance director.",
        extra_h="What a UK parent needs from the first finance leader",
        extra="IFRS and UK GAAP fluency, experience of a UK statutory audit, and the appetite to build a team rather than only run a process. The realistic pool is Chartered Accountants from UK-headquartered GCCs and the Big Four, plus a smaller group of ACCA and CIMA holders. We write down that universe, with current pay levels, before anyone is approached.",
        faqs=[("Can you find candidates with IFRS and UK statutory reporting experience?", "Yes. It is one of the deeper pools in India, concentrated in UK-parented GCCs and audit practices in Bengaluru, Gurugram and Mumbai.")],
    ),
    ("uae", "it-recruitment"): dict(
        angle="UAE businesses hire engineering and data people either into Dubai and Abu Dhabi or into an India team working Gulf hours. The two markets are ninety minutes apart.",
        extra_h="What is different about technology hiring for the Gulf",
        extra="For seats inside the UAE the question is whether the candidate will move and at what all-in package. For India-based seats it is whether they can work with a thin local team around them. Government, banking and logistics clients usually add data-residency and access requirements, which narrows the pool and belongs in the brief from day one.",
        faqs=[("Do you place engineers into Dubai or only in India?", "Both. Relocation searches are mostly India to UAE, and we confirm visa status, family position and all-in package expectations before shortlisting.")],
    ),
    ("uae", "finance-leadership-hiring"): dict(
        angle="Gulf finance leadership searches turn on group structure: several entities, several jurisdictions and a family or board shareholder who wants one clean number.",
        extra_h="What a Gulf group needs from a finance leader",
        extra="Consolidation across entities, comfort with thin systems, and the judgment to handle a shareholder relationship directly. DIFC and ADGM regulated firms add a reporting layer on top. For relocation candidates the decision is a family one, so we test schooling, spouse employment and the all-in AED package against what they keep in India today before a shortlist exists.",
        faqs=[("Can you run a confidential CFO search in the UAE?", "Yes, and most are. We approach candidates without naming the group until an NDA is signed, which matters in a market this closely connected.")],
    ),
    ("singapore", "it-recruitment"): dict(
        angle="For Singapore businesses an India engineering team is usually about depth of supply rather than cost, and the 2.5 hour difference gives you a shared working day.",
        extra_h="What is different about hiring India engineers from Singapore",
        extra="Fintech, trading and payments clients need people who have worked at volume and under audit, which narrows the pool to specific companies in Bengaluru, Hyderabad, Pune and Chennai. The overlap supports one team on one stand-up, so we screen hard for people who can work directly with Singapore product owners rather than through a lead.",
        faqs=[("Which Indian cities suit a Singapore-facing engineering team?", "Bengaluru for depth, Hyderabad and Pune for retention and cost, Chennai for platform and payments engineering. All of them work an 11am to 8pm IST day comfortably.")],
    ),
    ("singapore", "finance-leadership-hiring"): dict(
        angle="Singapore-headquartered groups usually hire an India controller or shared services head who owns the close for several countries and reports into the regional CFO.",
        extra_h="What a regional CFO needs from the India finance leader",
        extra="Multi-country reporting under IFRS, process discipline for a shared service centre, and the stomach to standardise what local teams currently do their own way. The pool is Chartered Accountants from Asia-Pacific shared service centres and the Big Four. We map it with current pay before any approach, because these candidates are retained hard by their employers.",
        faqs=[("Should the regional controller sit in Singapore or India?", "If the role needs the regulator, the auditors and the board in person, Singapore. If it owns process and people, India will usually buy you a more experienced person for the same cost.")],
    ),
    ("australia", "it-recruitment"): dict(
        angle="Australian engineering and data teams hire in India for supply, not price. The constraint is the time difference, which works from the Australian afternoon onwards.",
        extra_h="What is different about hiring India engineers from Australia",
        extra="Sydney and Melbourne mornings are the middle of the Indian night, so stand-ups move to the Australian afternoon and the India team owns its own morning. That needs people who can work unsupervised for half a day, which is a screening question rather than a management one. Perth clients have almost full overlap and can run a single team.",
        faqs=[("How do stand-ups work with the time difference?", "Most teams move the stand-up to 2pm or later in Sydney, which is 8.30am IST. Perth teams usually keep their existing schedule.")],
    ),
    ("australia", "finance-leadership-hiring"): dict(
        angle="For Australian businesses the senior India finance hire is usually an offshore delivery head or a controller running statutory reporting and the close for an Australian parent.",
        extra_h="What an Australian parent needs from the first finance leader",
        extra="IFRS is the shared standard, which helps. What matters more is whether the person can run an offshore team at a quality the Australian partners or the board will accept without re-reviewing everything. Accounting and advisory firms also need workpaper review discipline and client-confidentiality handling. We assess for both and say where a candidate is light.",
        faqs=[("Can you find leaders who have run Australian-facing offshore teams?", "Yes. That pool sits in Ahmedabad, Pune, Bengaluru and Hyderabad, in firms already delivering accounting and advisory work for Australian clients.")],
    ),
}

# ------------------------------------------------------ INDIA METRO CITIES
CITIES = {
    "mumbai": dict(
        name="Mumbai", slugpath="/india/mumbai-recruitment-agency",
        kw="recruitment agency in Mumbai",
        h1_b="Finance, analytics and leadership hiring in Mumbai.",
        lead="Mumbai pays for proximity to money. Banking, insurance, capital markets and the head offices of most Indian conglomerates sit inside twenty kilometres of each other, and so does the competition for every good finance hire.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent in Mumbai. We know what BKC pays against Powai, which candidates will take a Navi Mumbai commute, and what it costs to move someone out of a bank.",
        market_h="What the Mumbai market actually looks like.",
        market=["Financial services set the price. Banks, NBFCs, insurers, asset managers and the broking houses hire the same chartered accountants and FP&amp;A people you want, and they pay in bonus as well as fixed. A brief benchmarked against a manufacturing salary band will not land here.",
                "Geography decides acceptance. A candidate in Thane will think hard about a Lower Parel office, and a BKC role competes with every other BKC role on commute alone. We ask where people live before we shortlist them.",
                "Notice periods are long and counter-offers are normal. Ninety days is standard at manager level in financial services, and the counter-offer arrives at the exit interview. We stay close to candidates through the whole notice period."],
        sectors=[("Banking, NBFC &amp; capital markets", "Financial controller, product control, treasury, regulatory reporting, risk", "Manager to Director"),
                 ("Insurance &amp; asset management", "Actuarial support, fund accounting, investment reporting, compliance", "Analyst to Head"),
                 ("Conglomerate head offices", "Group reporting, consolidation, FP&amp;A, internal audit, M&amp;A support", "Manager to Director"),
                 ("Media, retail &amp; consumer", "Commercial finance, business partnering, revenue analytics", "Analyst to Senior Manager"),
                 ("Technology &amp; fintech", "Data engineers, analytics leads, ML engineers, platform engineering", "Mid to Head"),
                 ("Leadership", "CFO, finance director, head of FP&amp;A, analytics head", "Director to CFO")],
        hubs=["Bandra Kurla Complex", "Lower Parel", "Worli", "Andheri East", "Powai", "Goregaon", "Navi Mumbai", "Thane"],
        faqs=[("Which roles do you hire for in Mumbai?",
               "Finance and accounting, FP&amp;A, controllership, treasury and risk, analytics and data, AI and ML, and finance leadership up to CFO. We do not run volume or non-specialist hiring."),
              ("How long does a Mumbai search take?",
               "Four to six weeks from brief to signed offer for specialist roles, six to ten for leadership. Then expect a 90-day notice period, which is standard in financial services here."),
              ("Do you cover Navi Mumbai and Thane?",
               "Yes, as part of the same market, but we match on commute. A two-hour journey each way is the most common reason a Mumbai offer is declined."),
              ("Can you benchmark pay for a Mumbai role?",
               "Yes. We benchmark against the specific companies competing for the person, including the bonus and retention structures financial services employers use, and share the range before the search opens."),
              ("Do you work with GCCs in Mumbai?",
               "Yes, alongside Indian corporates, banks and startups. Mumbai GCC hiring concentrates in financial services, analytics and risk.")],
    ),
    "bangalore": dict(
        name="Bengaluru", alias="Bangalore", slugpath="/india/bangalore-recruitment-agency",
        kw="recruitment agency in Bangalore",
        h1_b="Finance, data and AI hiring in Bengaluru.",
        lead="We are based here, on Infantry Road. Bengaluru has the deepest technology and GCC talent pool in India and the highest churn to match, so the difference between a good hire and a quick exit sits almost entirely in the screening.",
        short="Stellaspire is a Bengaluru recruitment agency hiring finance, accounting, analytics, AI and leadership talent. We work from WeWork Prestige Central on Infantry Road and we know which companies pay, which teams churn and what a counter-offer looks like here.",
        market_h="What the Bengaluru market actually looks like.",
        market=["GCCs set the benchmark. Several hundred capability centres hire from the same pool, which keeps pay high and tenure short. For finance and analytics roles the realistic competition is almost always another GCC rather than an Indian corporate.",
                "The AI premium is real and still moving. Candidates with production LLM or platform experience are priced by funded startups and global product teams, so a band approved a year ago usually needs revisiting before the search opens.",
                "Commute is a live constraint. Whitefield to Electronic City is not a journey anyone makes twice. We shortlist on location as well as skill, which is also why our offer acceptance holds up."],
        sectors=[("GCC finance &amp; controllership", "Financial controller, R2R lead, FP&amp;A manager, reporting head", "Manager to Director"),
                 ("Data &amp; analytics", "Analytics manager, data scientist, data engineer, BI lead", "Senior IC to Head"),
                 ("AI &amp; ML", "ML engineer, applied scientist, LLM and platform engineers, MLOps", "Senior IC to Lead"),
                 ("Technology", "Backend, full-stack, DevOps, SRE, engineering manager", "Mid to Director"),
                 ("Startup finance", "Head of finance, controller, revenue and commercial finance", "Manager to Director"),
                 ("Leadership", "Site head, India finance head, analytics head, CFO", "Director to CFO")],
        hubs=["Whitefield", "Outer Ring Road", "Koramangala", "Indiranagar", "Electronic City", "Hebbal", "Bellandur", "Infantry Road and CBD"],
        faqs=[("Where are you based in Bengaluru?",
               "WeWork Prestige Central, 36 Infantry Road, Bengaluru 560001. Candidates and clients are welcome to meet us there."),
              ("Which roles do you hire for in Bengaluru?",
               "Finance and accounting, FP&amp;A, controllership, analytics and data, AI and ML, technology, and leadership roles up to CFO and site head."),
              ("How fast can you close a Bengaluru role?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership. Notice periods run 60 to 90 days at senior levels and shorter in startups."),
              ("Why is attrition so high here?",
               "Density. A candidate can change employer without changing their commute, and GCCs counter-offer aggressively. We screen for the reason behind the last two moves, which is the best available predictor."),
              ("Do you hire for startups as well as GCCs?",
               "Yes, and we brief the two differently. Startups need people who will build with no team under them; GCCs need people who can work with a global parent.")],
    ),
    "delhi-ncr": dict(
        name="Delhi NCR", slugpath="/india/delhi-ncr-recruitment-agency",
        kw="recruitment agency in Delhi NCR",
        h1_b="Hiring across Gurugram, Noida and Delhi.",
        lead="Delhi NCR is three hiring markets that share a metro line. Gurugram runs on GCCs and consulting, Noida on technology and services, Delhi on head offices and promoter-led businesses, and candidates move between them by commute as much as by career.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent across Delhi NCR, covering Gurugram, Noida, Greater Noida, Faridabad and Delhi. We match on commute and on the kind of company a candidate will actually thrive in.",
        market_h="What the Delhi NCR market actually looks like.",
        market=["Gurugram is the GCC and consulting belt. Cyber City, Golf Course Road and Udyog Vihar hold most of the finance, analytics and consulting talent, and pay is benchmarked against global parents rather than local ones.",
                "Noida and Greater Noida are stronger on technology, services and shared service centres, usually at a lower cost base and with better retention. For process-heavy finance work it is often the better choice.",
                "Promoter-led businesses in Delhi hire differently. The decision maker is frequently the owner, the process is fast, and the fit question is about working style rather than structure. We brief candidates honestly about that before an interview."],
        sectors=[("GCC finance &amp; controllership", "Controller, R2R lead, FP&amp;A manager, reporting head", "Manager to Director"),
                 ("Consulting &amp; advisory", "Transaction services, internal audit, risk advisory, finance transformation", "Consultant to Director"),
                 ("Data &amp; analytics", "Analytics manager, data scientist, data engineer, BI lead", "Senior IC to Head"),
                 ("AI &amp; ML", "ML engineers, applied scientists, data platform engineers", "Senior IC to Lead"),
                 ("Corporate &amp; promoter-led", "Group finance, treasury, commercial finance, internal audit", "Manager to Director"),
                 ("Leadership", "CFO, finance director, centre head, analytics head", "Director to CFO")],
        hubs=["Cyber City, Gurugram", "Golf Course Road", "Udyog Vihar", "Noida Sector 62", "Noida Sector 125", "Greater Noida", "Aerocity", "Faridabad"],
        faqs=[("Does NCR mean Gurugram only?",
               "No. We hire across Gurugram, Noida, Greater Noida, Faridabad, Ghaziabad and Delhi. Where the office sits matters a great deal to acceptance, so we match on it deliberately."),
              ("Which roles do you hire for in Delhi NCR?",
               "Finance and accounting, FP&amp;A, controllership, consulting and advisory, analytics and data, AI and ML, and leadership roles up to CFO."),
              ("Is Gurugram pay higher than Noida?",
               "Usually, for the same role, because the employer set is different. We benchmark by micro-market rather than quoting one NCR number."),
              ("How long does a search take here?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period at senior levels."),
              ("Do you hire for promoter-led companies?",
               "Yes, and we brief candidates plainly on what that environment asks of them. Mismatched expectations are the main reason these offers fall through.")],
    ),
    "hyderabad": dict(
        name="Hyderabad", slugpath="/india/hyderabad-recruitment-agency",
        kw="recruitment agency in Hyderabad",
        h1_b="GCC finance, data and AI hiring in Hyderabad.",
        lead="Hyderabad has become the default second city for GCCs, and for good reason: the talent is strong, the cost base sits below Bengaluru and people stay longer. The pool thins at the very top, which changes how a senior search has to be run.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent in Hyderabad. We know the HITEC City and Gachibowli employer set, what it pays against Bengaluru, and when a senior role needs a relocation search.",
        market_h="What the Hyderabad market actually looks like.",
        market=["Cost and retention are the draw. For the same finance or analytics role, Hyderabad usually lands below Bengaluru on fixed pay and holds people longer. For shared service and controllership work that combination is hard to beat.",
                "The employer set is concentrated. HITEC City, Gachibowli and the Financial District hold most of the GCCs, pharmaceutical head offices and product companies, which makes the realistic competition for a candidate easy to name and easy to benchmark.",
                "Senior supply is thinner than Bengaluru. For director-level finance and analytics roles we usually run a dual search: local candidates alongside people willing to relocate from Bengaluru, Chennai or Pune, frequently returning home."],
        sectors=[("GCC finance &amp; shared services", "Controller, R2R and P2P leads, FP&amp;A manager, process owners", "Manager to Director"),
                 ("Pharma &amp; life sciences finance", "Plant finance, costing, commercial finance, regulatory reporting", "Analyst to Head"),
                 ("Data &amp; analytics", "Analytics manager, data scientist, data engineer, BI lead", "Senior IC to Head"),
                 ("AI &amp; ML", "ML engineers, applied scientists, platform and MLOps engineers", "Senior IC to Lead"),
                 ("Technology", "Backend, cloud, DevOps, QA automation, engineering manager", "Mid to Director"),
                 ("Leadership", "Site head, finance head, analytics head, shared services director", "Director to VP")],
        hubs=["HITEC City", "Gachibowli", "Financial District", "Madhapur", "Kondapur", "Banjara Hills", "Uppal", "Shamshabad"],
        faqs=[("Why hire in Hyderabad instead of Bengaluru?",
               "Lower cost for the same role across most finance and analytics functions, and better retention. The trade-off is a thinner pool at director level and above, which we solve with a relocation search."),
              ("Which roles do you hire for in Hyderabad?",
               "GCC finance and shared services, controllership, FP&amp;A, analytics and data, AI and ML, technology, and leadership roles up to site head."),
              ("Can you find people willing to relocate to Hyderabad?",
               "Yes, and it is often the fastest route for senior roles. Many candidates in Bengaluru and Chennai have family in Telangana or Andhra Pradesh and will move for the right role."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period."),
              ("Do you cover pharma and life sciences finance?",
               "Yes. Plant finance, costing and commercial finance for the pharmaceutical companies headquartered here is a regular part of our Hyderabad work.")],
    ),
    "pune": dict(
        name="Pune", slugpath="/india/pune-recruitment-agency",
        kw="recruitment agency in Pune",
        h1_b="Finance, analytics and engineering hiring in Pune.",
        lead="Pune is the quiet workhorse of Indian hiring: manufacturing head offices, automotive engineering, GCCs in Hinjawadi and Kharadi, and a candidate base that tends to stay put. It is where cost-conscious teams go when Bengaluru stops making sense.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent in Pune. We cover the Hinjawadi and Kharadi GCC belt and the manufacturing and automotive finance market, and we know what each one pays.",
        market_h="What the Pune market actually looks like.",
        market=["Two markets in one city. The GCC belt in Hinjawadi, Kharadi and Magarpatta hires like Bengaluru, slightly cheaper. The manufacturing and automotive corridor hires on plant finance, costing and engineering, and pays on a different curve entirely.",
                "Retention is the real advantage. Pune candidates move less often than Bengaluru candidates at the same level, partly because the alternative employer is usually across town rather than across the road.",
                "Commute splits the city. Hinjawadi to Kharadi is a decision, not a detail. We shortlist on where a candidate lives, which is also why Pune offers close more predictably."],
        sectors=[("GCC finance &amp; shared services", "Controller, R2R lead, FP&amp;A manager, process owners", "Manager to Director"),
                 ("Manufacturing &amp; automotive finance", "Plant finance, costing, commercial finance, capex and project finance", "Analyst to Head"),
                 ("Engineering &amp; technology", "Embedded, backend, cloud, DevOps, engineering manager", "Mid to Director"),
                 ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, data scientist", "Senior IC to Head"),
                 ("Outsourced accounting", "Accounts preparation, bookkeeping leads, workpaper reviewers for UK, US and Australian clients", "Associate to Manager"),
                 ("Leadership", "Finance head, plant CFO, centre head, analytics head", "Director to CFO")],
        hubs=["Hinjawadi", "Kharadi", "Magarpatta", "Baner", "Viman Nagar", "Chakan", "Talegaon", "Pimpri-Chinchwad"],
        faqs=[("Which roles do you hire for in Pune?",
               "GCC finance and shared services, manufacturing and plant finance, costing, FP&amp;A, analytics and data, AI and ML, engineering, and leadership roles."),
              ("Is Pune cheaper than Bengaluru?",
               "For most finance and analytics roles, yes, usually by a meaningful margin at the same level, with better retention. Senior supply is thinner, so director-level searches sometimes need relocation candidates."),
              ("Do you cover the manufacturing belt?",
               "Yes. Chakan, Talegaon and Pimpri-Chinchwad plant finance and costing roles are a regular part of our Pune work, and they need a different screen from GCC finance."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period."),
              ("Can you hire outsourced accounting teams in Pune?",
               "Yes. Pune has a deep pool of accountants already working on UK, US and Australian client books, which suits firms building an offshore delivery team.")],
    ),
    "chennai": dict(
        name="Chennai", slugpath="/india/chennai-recruitment-agency",
        kw="recruitment agency in Chennai",
        h1_b="Finance, analytics and engineering hiring in Chennai.",
        lead="Chennai hires on depth rather than noise. Manufacturing and automotive head offices, a large captive finance and insurance base along OMR, and engineering talent that stays in the same job for years.",
        short="Stellaspire hires finance, accounting, analytics, AI and leadership talent in Chennai. We cover the OMR captive belt, the manufacturing corridor and the Guindy and Nungambakkam corporate market.",
        market_h="What the Chennai market actually looks like.",
        market=["Retention is the best among the big five cities. Chennai candidates change employer less often than those in Bengaluru or Gurugram, which makes the city a strong choice for process-heavy finance and long-cycle engineering work.",
                "OMR is its own employer set. The captive centres for banking, insurance and technology along Old Mahabalipuram Road hire most of the finance, analytics and platform talent, and benchmark against each other rather than against local corporates.",
                "Manufacturing finance is a genuine specialism here. Plant finance, costing and inventory controllership roles need candidates from the automotive and engineering corridor rather than from a GCC, and the two pools do not substitute for each other."],
        sectors=[("Captive finance &amp; shared services", "Controller, R2R lead, FP&amp;A manager, process owners", "Manager to Director"),
                 ("Manufacturing &amp; automotive finance", "Plant finance, costing, inventory control, capex finance", "Analyst to Head"),
                 ("Banking &amp; insurance operations", "Fund accounting, regulatory reporting, reconciliations, risk analytics", "Analyst to Head"),
                 ("Technology &amp; platform", "Backend, platform, embedded, DevOps, engineering manager", "Mid to Director"),
                 ("Data &amp; analytics", "Analytics manager, data engineer, data scientist, BI lead", "Senior IC to Head"),
                 ("Leadership", "Finance head, plant CFO, centre head, analytics head", "Director to CFO")],
        hubs=["Old Mahabalipuram Road", "Guindy", "Nungambakkam", "Ambattur", "Sriperumbudur", "Oragadam", "Perungudi", "Taramani"],
        faqs=[("Which roles do you hire for in Chennai?",
               "Captive and shared service finance, manufacturing and plant finance, costing, banking and insurance operations, analytics and data, AI and ML, engineering, and leadership roles."),
              ("Is Chennai good for manufacturing finance?",
               "It is one of the strongest markets in India for it. The automotive and engineering corridor around Sriperumbudur and Oragadam has a deep pool of plant finance and costing specialists."),
              ("Do candidates here expect to relocate?",
               "Less than in other cities. Chennai candidates tend to stay in Chennai, which helps retention and limits the pool for senior roles. Relocation searches usually target people returning home from Bengaluru or the Gulf."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period."),
              ("Do you hire for OMR captives?",
               "Yes. Finance, analytics and platform roles for the banking, insurance and technology captives along OMR are a regular part of our Chennai work.")],
    ),
    "ahmedabad": dict(
        name="Ahmedabad", slugpath="/india/ahmedabad-recruitment-agency",
        kw="recruitment agency in Ahmedabad",
        h1_b="Finance, accounting and offshore delivery hiring in Ahmedabad.",
        lead="Ahmedabad is the best value finance market in India and most people outside Gujarat underrate it: a deep chartered accountant base, a large offshore accounting industry serving UK, US and Australian firms, and GIFT City pulling in financial services.",
        short="Stellaspire hires finance, accounting, analytics and leadership talent in Ahmedabad and Gandhinagar, including GIFT City. It is the strongest value market in India for offshore accounting and controllership teams.",
        market_h="What the Ahmedabad market actually looks like.",
        market=["The chartered accountant base is the story. Gujarat produces a large number of CAs and many of them stay, giving Ahmedabad unusual depth in accounting and controllership at a cost well below Bengaluru or Mumbai.",
                "Offshore accounting is already an industry here. Dozens of firms deliver bookkeeping, accounts preparation and tax support for UK, US and Australian clients, so candidates arrive fluent in Xero, QuickBooks, Sage and client workpaper discipline.",
                "GIFT City changes the senior end. The international financial services centre in Gandhinagar is pulling banking, insurance and fund administration roles into the market, which has started to lift pay for regulated-finance experience."],
        sectors=[("Accounting &amp; controllership", "Financial controller, chief accountant, R2R lead, chartered accountants", "Manager to Director"),
                 ("Offshore accounting delivery", "Accounts preparation, bookkeeping leads, workpaper reviewers, tax support", "Associate to Manager"),
                 ("GIFT City financial services", "Fund accounting, regulatory reporting, compliance, treasury operations", "Analyst to Head"),
                 ("Manufacturing &amp; pharma finance", "Plant finance, costing, commercial finance, exports and trade finance", "Analyst to Head"),
                 ("Data &amp; analytics", "Analytics manager, data engineer, BI lead", "Senior IC to Head"),
                 ("Leadership", "Finance head, delivery head, CFO for a promoter-led group", "Director to CFO")],
        hubs=["GIFT City, Gandhinagar", "Prahlad Nagar", "SG Highway", "Bodakdev", "Ashram Road", "Sanand", "Changodar", "Gandhinagar"],
        faqs=[("Why hire finance roles in Ahmedabad?",
               "Depth of chartered accountant supply at a cost well below Bengaluru, Mumbai or Gurugram, with better retention. For controllership and offshore accounting delivery it is frequently the best value in India."),
              ("Can you hire offshore accounting teams for UK, US or Australian firms?",
               "Yes, and it is one of the city's strengths. Candidates here routinely work on overseas client books in Xero, QuickBooks and Sage, with workpaper review experience."),
              ("Do you hire for GIFT City?",
               "Yes. Fund accounting, regulatory reporting, compliance and treasury operations roles in the Gandhinagar international financial services centre, usually with a relocation search running alongside local candidates."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership. Notice periods are often shorter than in Bengaluru or Mumbai."),
              ("Do candidates work comfortably with overseas clients?",
               "At manager level and above, yes. The offshore accounting industry here has trained a generation of accountants to work directly with UK, US and Australian clients.")],
    ),
    "kolkata": dict(
        name="Kolkata", slugpath="/india/kolkata-recruitment-agency",
        kw="recruitment agency in Kolkata",
        h1_b="Finance, accounting and analytics hiring in Kolkata.",
        lead="Kolkata has a strong chartered accountant tradition, an established shared services base in Salt Lake Sector V and New Town, and a cost structure that makes process-heavy finance work land well. The senior pool is thinner, and that shapes how we run a search.",
        short="Stellaspire hires finance, accounting, analytics and leadership talent in Kolkata, covering Salt Lake Sector V, New Town and the central business district. Strong value for controllership and shared service work.",
        market_h="What the Kolkata market actually looks like.",
        market=["The accounting base is deep and loyal. Kolkata's chartered accountant and cost accountant community is long established, and candidates tend to stay with an employer for years rather than months.",
                "Shared services sit in Salt Lake Sector V and New Town. Most GCC and shared service hiring happens there, with pay benchmarked below Bengaluru and Hyderabad for comparable roles.",
                "Senior searches often need relocation candidates. For director-level finance and analytics roles the local pool is limited, so we run local and returning-home candidates in parallel, usually from Bengaluru, Mumbai or the Gulf."],
        sectors=[("Accounting &amp; controllership", "Financial controller, chief accountant, R2R lead, chartered and cost accountants", "Manager to Director"),
                 ("Shared services", "P2P and O2C process leads, reconciliations, reporting analysts", "Associate to Manager"),
                 ("Manufacturing &amp; infrastructure finance", "Plant finance, costing, project finance, commercial finance", "Analyst to Head"),
                 ("Data &amp; analytics", "Analytics manager, data engineer, BI lead, reporting analytics", "Senior IC to Head"),
                 ("Technology", "Backend, full-stack, QA, support engineering", "Mid to Lead"),
                 ("Leadership", "Finance head, shared services head, CFO for a regional group", "Director to CFO")],
        hubs=["Salt Lake Sector V", "New Town Rajarhat", "Park Street", "Camac Street", "Bantala", "Howrah", "Dankuni", "Taratala"],
        faqs=[("Which roles do you hire for in Kolkata?",
               "Accounting and controllership, shared service process roles, manufacturing and infrastructure finance, analytics and data, technology, and finance leadership."),
              ("Is Kolkata a good location for a shared service centre?",
               "For process-heavy finance work, yes. Cost sits below Bengaluru and Hyderabad, retention is better and accounting supply is strong. Senior leadership is where you will need to look wider."),
              ("Can you find senior finance leaders in Kolkata?",
               "Yes, usually by running local candidates alongside people willing to return from Bengaluru, Mumbai or the Gulf. Returning-home candidates close well here."),
              ("How long does a search take?",
               "Four to six weeks to a signed offer for specialist roles, six to ten for leadership, plus a 60 to 90 day notice period."),
              ("Do you cover Howrah and the industrial belt?",
               "Yes. Plant finance, costing and project finance roles around Howrah, Dankuni and Taratala are part of the same market, and they need a manufacturing screen rather than a shared services one.")],
    ),
}

# ------------------------------- American spelling pass for the /us pages
SPELL_US = [
    ("organisation", "organization"), ("Organisation", "Organization"),
    ("organise", "organize"),
    # stems only, never "specialist" -- that word is identical in both spellings
    ("specialise", "specialize"), ("specialising", "specializing"), ("specialised", "specialized"),
    ("Specialise", "Specialize"), ("Specialised", "Specialized"),
    ("recognise", "recognize"), ("recognised", "recognized"),
    ("prioritise", "prioritize"), ("standardise", "standardize"), ("standardised", "standardized"),
    ("stabilise", "stabilize"), ("stabilisation", "stabilization"),
    ("utilise", "utilize"), ("analyse", "analyze"), ("analysed", "analyzed"),
    ("centre", "center"), ("Centre", "Center"), ("programme", "program"),
    ("labour", "labor"), ("behaviour", "behavior"), ("favour", "favor"),
    ("licence", "license"), ("modelling", "modeling"), ("fulfil ", "fulfill "),
    ("whilst", "while"), ("judgement", "judgment"), ("practise", "practice"),
    ("CVs", "resumes"), ("CV", "resume"),
]
